<?php
/**
 * /Users/trailo/dev/aecore/app/appzioUI/console/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 *
 * @var yii\web\View $this
 * @var backend\modules\quizzes\models\AeExtQuizQuestionAnswer $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="ae-ext-quiz-question-answer-form">

    <?php $form = ActiveForm::begin([
		'id' => 'AeExtQuizQuestionAnswer',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-danger',
		'fieldConfig' => [
			'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
			'horizontalCssClasses' => [
				'label' => 'col-sm-2',
				//'offset' => 'col-sm-offset-4',
				'wrapper' => 'col-sm-8',
				'error' => '',
				'hint' => '',
			],
		],
	]
);
?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


<!-- attribute question_id -->
			<?php echo $form->field($model, 'question_id')->textInput() ?>

<!-- attribute answer_id -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'answer_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(backend\modules\quizzes\models\AeExtQuizQuestion::find()->all(), 'id', 'title'),
	[
		'prompt' => 'Select',
		'disabled' => (isset($relAttributes) && isset($relAttributes['answer_id'])),
	]
); ?>

<!-- attribute answer -->
			<?php echo $form->field($model, 'answer')->textarea(['rows' => 6]) ?>

<!-- attribute play_id -->
			<?php echo $form->field($model, 'play_id')->textInput() ?>

<!-- attribute comment -->
			<?php echo $form->field($model, 'comment')->textarea(['rows' => 6]) ?>

<!-- attribute date_created -->
			<?php echo $form->field($model, 'date_created')->textInput() ?>

<!-- attribute question -->
        </p>
        <?php $this->endBlock(); ?>

        <?php echo
Tabs::widget(
	[
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => Yii::t('backend', 'AeExtQuizQuestionAnswer'),
				'content' => $this->blocks['main'],
				'active'  => true,
			],
		]
	]
);
?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?php echo Html::submitButton(
	'<span class="glyphicon glyphicon-check"></span> ' .
	($model->isNewRecord ? 'Create' : 'Save'),
	[
		'id' => 'save-' . $model->formName(),
		'class' => 'btn btn-success'
	]
);
?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
