<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\golf\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_golf_hole_user".
 *
 * @property string $id
 * @property string $hole_id
 * @property string $event_id
 * @property string $play_id
 * @property integer $strokes
 * @property string $comments
 * @property string $aliasModel
 */
abstract class AeExtGolfHoleUser extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_golf_hole_user';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['hole_id', 'event_id', 'play_id', 'strokes', 'comments'], 'required'],
            [['hole_id', 'event_id', 'play_id', 'strokes'], 'integer'],
            [['comments'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'hole_id' => Yii::t('backend', 'Hole ID'),
            'event_id' => Yii::t('backend', 'Event ID'),
            'play_id' => Yii::t('backend', 'Play ID'),
            'strokes' => Yii::t('backend', 'Strokes'),
            'comments' => Yii::t('backend', 'Comments'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\golf\models\query\AeExtGolfHoleUserQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\golf\models\query\AeExtGolfHoleUserQuery(get_called_class());
    }


}
