<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\golf\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_mobileevents".
 *
 * @property string $id
 * @property string $game_id
 * @property string $play_id
 * @property string $place_id
 * @property string $title
 * @property string $date
 * @property string $time
 * @property string $time_of_day
 * @property string $status
 * @property string $notes
 * @property string $starting_time
 * @property string $aliasModel
 */
abstract class AeExtMobileevent extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_mobileevents';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['game_id', 'play_id', 'place_id', 'title', 'date', 'time', 'time_of_day', 'status', 'notes', 'starting_time'], 'required'],
            [['game_id', 'play_id', 'place_id'], 'integer'],
            [['date', 'time', 'starting_time'], 'safe'],
            [['title', 'notes'], 'string', 'max' => 255],
            [['time_of_day', 'status'], 'string', 'max' => 20]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'game_id' => Yii::t('backend', 'Game ID'),
            'play_id' => Yii::t('backend', 'Play ID'),
            'place_id' => Yii::t('backend', 'Place ID'),
            'title' => Yii::t('backend', 'Title'),
            'date' => Yii::t('backend', 'Date'),
            'time' => Yii::t('backend', 'Time'),
            'time_of_day' => Yii::t('backend', 'Time Of Day'),
            'status' => Yii::t('backend', 'Status'),
            'notes' => Yii::t('backend', 'Notes'),
            'starting_time' => Yii::t('backend', 'Starting Time'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\golf\models\query\AeExtMobileeventQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\golf\models\query\AeExtMobileeventQuery(get_called_class());
    }


}
