<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\golf\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_game_role".
 *
 * @property string $id
 * @property string $game_id
 * @property string $name
 *
 * @property \backend\modules\golf\models\AeGameBranchAction[] $aeGameBranchActions
 * @property string $aliasModel
 */
abstract class AeGameRole extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_game_role';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['game_id', 'name'], 'required'],
            [['game_id'], 'integer'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'game_id' => Yii::t('backend', 'Game ID'),
            'name' => Yii::t('backend', 'Name'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAeGameBranchActions()
    {
        return $this->hasMany(\backend\modules\golf\models\AeGameBranchAction::className(), ['role_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\golf\models\query\AeGameRoleQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\golf\models\query\AeGameRoleQuery(get_called_class());
    }


}
