<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\golf\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_location_log".
 *
 * @property string $id
 * @property string $game_id
 * @property string $play_id
 * @property string $beacon_id
 * @property string $place_id
 * @property string $lat
 * @property string $lon
 * @property string $date
 * @property string $aliasModel
 */
abstract class AeLocationLog extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_location_log';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['game_id', 'lat', 'lon'], 'required'],
            [['game_id', 'play_id', 'beacon_id', 'place_id'], 'integer'],
            [['lat', 'lon'], 'number'],
            [['date'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'game_id' => Yii::t('backend', 'Game ID'),
            'play_id' => Yii::t('backend', 'Play ID'),
            'beacon_id' => Yii::t('backend', 'Beacon ID'),
            'place_id' => Yii::t('backend', 'Place ID'),
            'lat' => Yii::t('backend', 'Lat'),
            'lon' => Yii::t('backend', 'Lon'),
            'date' => Yii::t('backend', 'Date'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\golf\models\query\AeLocationLogQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\golf\models\query\AeLocationLogQuery(get_called_class());
    }


}
