<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\products\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_products_categories".
 *
 * @property integer $id
 * @property integer $app_id
 * @property integer $sorting
 * @property string $title
 * @property string $headertext
 * @property string $icon
 *
 * @property \backend\modules\products\models\AeExtProduct[] $aeExtProducts
 * @property \backend\modules\products\models\AeGame $app
 * @property string $aliasModel
 */
abstract class AeExtProductsCategory extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_products_categories';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['app_id', 'sorting', 'title', 'headertext', 'icon'], 'required'],
            [['app_id', 'sorting'], 'integer'],
            [['title', 'headertext', 'icon'], 'string', 'max' => 255],
            [['app_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\products\models\AeGame::className(), 'targetAttribute' => ['app_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'app_id' => Yii::t('backend', 'App ID'),
            'sorting' => Yii::t('backend', 'Sorting'),
            'title' => Yii::t('backend', 'Title'),
            'headertext' => Yii::t('backend', 'Headertext'),
            'icon' => Yii::t('backend', 'Icon'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAeExtProducts()
    {
        return $this->hasMany(\backend\modules\products\models\AeExtProduct::className(), ['category_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getApp()
    {
        return $this->hasOne(\backend\modules\products\models\AeGame::className(), ['id' => 'app_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\products\models\query\AeExtProductsCategoryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\products\models\query\AeExtProductsCategoryQuery(get_called_class());
    }


}
