<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\places\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_club_news".
 *
 * @property string $id
 * @property string $club_id
 * @property string $name
 * @property string $description
 * @property string $photo
 * @property string $link_url
 * @property string $timestamp
 *
 * @property \backend\modules\places\models\AeExtMobileplace $club
 * @property string $aliasModel
 */
abstract class AeExtClubNews extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_club_news';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
	        [['club_id', 'name', 'description', 'link_url'], 'required'],
            [['club_id'], 'integer'],
            [['description'], 'string'],
            [['name', 'link_url'], 'string', 'max' => 255],
            [['club_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\places\models\AeExtMobileplace::className(), 'targetAttribute' => ['club_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'club_id' => Yii::t('backend', 'Club ID'),
            'name' => Yii::t('backend', 'Name'),
            'description' => Yii::t('backend', 'Description'),
            'photo' => Yii::t('backend', 'Photo'),
            'link_url' => Yii::t('backend', 'Link Url'),
            'timestamp' => Yii::t('backend', 'Timestamp'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClub()
    {
        return $this->hasOne(\backend\modules\places\models\AeExtMobileplace::className(), ['id' => 'club_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\places\models\query\AeExtClubNewsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\places\models\query\AeExtClubNewsQuery(get_called_class());
    }


}
