<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\places\controllers\base;

use backend\modules\places\models\AeExtMobileplace;
    use backend\modules\places\search\AeExtMobileplace as AeExtMobileplaceSearch;
use backend\controllers\CrudBaseController;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;
use yii\web\UploadedFile;
use backend\components\Helper;

/**
* AeExtMobileplaceController implements the CRUD actions for AeExtMobileplace model.
*/
class AeExtMobileplaceController extends CrudBaseController
{


/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;


/**
* Lists all AeExtMobileplace models.
* @return mixed
*/
public function actionIndex()
{
    $searchModel  = new AeExtMobileplaceSearch;
    $dataProvider = $searchModel->search($_GET);

Tabs::clearLocalStorage();

Url::remember();
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->render('index', [
'dataProvider' => $dataProvider,
    'searchModel' => $searchModel,
]);
}

/**
* Displays a single AeExtMobileplace model.
* @param string $id
*
* @return mixed
*/
public function actionView($id)
{
\Yii::$app->session['__crudReturnUrl'] = Url::previous();
Url::remember();
Tabs::rememberActiveState();

return $this->render('view', [
'model' => $this->findModel($id),
]);
}

/**
* Creates a new AeExtMobileplace model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
$model = new AeExtMobileplace;

$model = $this->addImageUploads( $model );

try {
if ($model->load($_POST) && $model->save()) {
return $this->redirect(['view', 'id' => $model->id]);
} elseif (!\Yii::$app->request->isPost) {
$model->load($_GET);
}
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
$model->addError('_exception', $msg);
}
return $this->render('create', ['model' => $model]);
}

/**
* Updates an existing AeExtMobileplace model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param string $id
* @return mixed
*/
public function actionUpdate($id)
{
$model = $this->findModel($id);

$model = $this->addImageUploads( $model );

if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing AeExtMobileplace model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param string $id
* @return mixed
*/
public function actionDelete($id)
{
try {
$this->findModel($id)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$id',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the AeExtMobileplace model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param string $id
* @return AeExtMobileplace the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($id)
{
if (($model = AeExtMobileplace::findOne($id)) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}

	protected function addImageUploads( $model ) {

		$image_files = array(
			'logo', 'headerimage1', 'headerimage2', 'headerimage3'
		);

		foreach ( $image_files as $image_file ) {

			if ( !isset($_FILES['AeExtMobileplace']['name'][$image_file]) OR empty($_FILES['AeExtMobileplace']['name'][$image_file]) ) {
				continue;
			}

			$destination = Helper::getUploadPath();

			if ( $destination ) {
				$file = UploadedFile::getInstance($model, $image_file);
				copy($file->tempName, $destination . $file->name);

				$model->{$image_file} = $file->name;
			}

		}

		return $model;
	}

}