<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\registration\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_mregister_companies_users".
 *
 * @property integer $id
 * @property integer $app_id
 * @property integer $company_id
 * @property integer $play_id
 * @property integer $registered
 * @property string $firstname
 * @property string $lastname
 * @property string $department
 * @property string $email
 * @property string $phone
 * @property string $registered_date
 * @property string $importFile
 *
 * @property \backend\modules\registration\models\AeExtMregisterCompany $company
 * @property \backend\modules\registration\models\AeGame $app
 * @property \backend\modules\registration\models\AeGamePlay $play
 * @property string $aliasModel
 */
abstract class AeExtMregisterCompaniesUser extends \backend\models\CrudBase
{

    public $importFile;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_mregister_companies_users';
    }

    /**
     * @inheritdoc
     */


    /*Error on line: a:1:{i:0;s:23:"App ID cannot be blank.";}
Error on line: a:1:{i:0;s:27:"Registered cannot be blank.";}
Error on line: a:1:{i:0;s:27:"Department cannot be blank.";}
Error on line: a:1:{i:0;s:22:"Phone cannot be blank.";}
Error on line: a:1:{i:0;s:32:"Registered Date cannot be blank.";}
Error on line: a:1:{i:0;s:23:"App ID cannot be blank.";}
Error on line: a:1:{i:0;s:27:"Registered cannot be blank.";}
Error on line: a:1:{i:0;s:27:"Department cannot be blank.";}
Error on line: a:1:{i:0;s:22:"Phone cannot be blank.";}
Error on line: a:1:{i:0;s:32:"Registered Date cannot be blank.";}
*/
    public function rules()
    {
        return [
            [['app_id', 'email'], 'required'],
            [['app_id', 'company_id', 'play_id', 'registered'], 'integer'],
            [['registered_date'], 'safe'],
            [['importFile'],'file','extensions' => 'csv'],
            [['firstname', 'lastname', 'department', 'email', 'phone'], 'string', 'max' => 255],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\registration\models\AeExtMregisterCompany::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['app_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\registration\models\AeGame::className(), 'targetAttribute' => ['app_id' => 'id']],
            [['play_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\registration\models\AeGamePlay::className(), 'targetAttribute' => ['play_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'app_id' => Yii::t('backend', 'App ID'),
            'company_id' => Yii::t('backend', 'Company ID'),
            'play_id' => Yii::t('backend', 'Play ID'),
            'registered' => Yii::t('backend', 'Registered'),
            'firstname' => Yii::t('backend', 'Firstname'),
            'lastname' => Yii::t('backend', 'Lastname'),
            'department' => Yii::t('backend', 'Department'),
            'email' => Yii::t('backend', 'Email'),
            'phone' => Yii::t('backend', 'Phone'),
            'registered_date' => Yii::t('backend', 'Registered Date'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\backend\modules\registration\models\AeExtMregisterCompany::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getApp()
    {
        return $this->hasOne(\backend\modules\registration\models\AeGame::className(), ['id' => 'app_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlay()
    {
        return $this->hasOne(\backend\modules\registration\models\AeGamePlay::className(), ['id' => 'play_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\registration\models\query\AeExtMregisterCompaniesUserQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\registration\models\query\AeExtMregisterCompaniesUserQuery(get_called_class());
    }


}
