<?php
/**
 * /Users/trailo/dev/aecore/app/appzioUI/console/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use backend\modules\fitness\models\AeGame;
use kartik\select2\Select2;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;
use zhuravljov\yii\widgets\DatePicker;
use zhuravljov\yii\widgets\DateTimePicker;

/**
 *
 * @var yii\web\View $this
 * @var backend\modules\registration\models\AeExtMregisterCompany $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="ae-ext-mregister-company-form">

    <?php $form = ActiveForm::begin([
            'id' => 'AeExtMregisterCompany',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-danger',
            'fieldConfig' => [
                'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
                'horizontalCssClasses' => [
                    'label' => 'col-sm-2',
                    //'offset' => 'col-sm-offset-4',
                    'wrapper' => 'col-sm-8',
                    'error' => '',
                    'hint' => '',
                ],
            ],
        ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
        <!-- attribute app_id -->
        <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
        $form->field($model, 'app_id')->dropDownList(
            \yii\helpers\ArrayHelper::map(backend\modules\fitness\models\AeGame::find()->all(), 'id', 'name'),
            [
                'prompt' => Yii::t('backend', 'Select'),
                'value' => isset($_SESSION['app_id']) ? $_SESSION['app_id'] : '',
                'disabled' => false,
            ]
        ); ?>

            <!-- attribute name -->
            <?php echo $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

            <!-- attribute subscription_active -->

            <?= $form->field($model, 'subscription_active')->checkbox([], false); ?>

            <!-- attribute subscription_expires -->
            <?= $form->field($model, 'subscription_expires')->widget(DatePicker::class, [
                // if you are using bootstrap, the following line will set the correct style of the input field
                'options' => ['class' => 'form-control'],
                // ... you can configure more DatePicker properties here
            ]) ?>

            <!-- attribute user_limit -->
            <?php echo $form->field($model, 'user_limit')->textInput() ?>


            <?= $form->field($model, 'admit_by_domain')->checkbox([], false); ?>
            <?php echo $form->field($model, 'domain')->textInput() ?>

            <!-- attribute notes -->
            <?php echo $form->field($model, 'notes')->textarea(['rows' => 6]) ?>
        </p>
        <?php $this->endBlock(); ?>

        <?php echo
        Tabs::widget(
            [
                'encodeLabels' => false,
                'items' => [
                    [
                        'label' => Yii::t('backend', 'AeExtMregisterCompany'),
                        'content' => $this->blocks['main'],
                        'active' => true,
                    ],
                ]
            ]
        );
        ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?php echo Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Save')),
            [
                'id' => 'save-' . $model->formName(),
                'class' => 'btn btn-success'
            ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
