<?php
/**
 * /Users/trailo/dev/aecore/app/appzioUI/console/runtime/giiant/d4b4964a63cc95065fa0ae19074007ee
 *
 * @package default
 */


use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
 *
 * @var yii\web\View $this
 * @var backend\modules\registration\models\AeExtMregisterCompany $model
 */
$copyParams = $model->attributes;

$this->title = Yii::t('backend', 'Licensed Companies');
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Ae Ext Mregister Companies'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('backend', 'View');
?>
<div class="giiant-crud ae-ext-mregister-company-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?php echo \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?php echo Yii::t('backend', 'Licensed Companies') ?>
        <small>
            <?php echo Html::encode($model->name) ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?php echo Html::a(
	'<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('backend', 'Edit'),
	[ 'update', 'id' => $model->id],
	['class' => 'btn btn-info']) ?>

            <?php echo Html::a(
	'<span class="glyphicon glyphicon-copy"></span> ' . Yii::t('backend', 'Copy'),
	['create', 'id' => $model->id, 'AeExtMregisterCompany'=>$copyParams],
	['class' => 'btn btn-success']) ?>

            <?php echo Html::a(
	'<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('backend', 'New'),
	['create'],
	['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?php echo Html::a('<span class="glyphicon glyphicon-list"></span> '
	. Yii::t('backend', 'Full list'), ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('backend\modules\registration\models\AeExtMregisterCompany'); ?>


    <?php echo DetailView::widget([
		'model' => $model,
		'attributes' => [
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'app_id',
				'value' => ($model->app ?
					Html::a('<i class="glyphicon glyphicon-list"></i>', ['/registration/ae-game/index']).' '.
					Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->app->name, ['/registration/ae-game/view', 'id' => $model->app->id, ]).' '.
					Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'AeExtMregisterCompany'=>['app_id' => $model->app_id]])
					:
					'<span class="label label-warning">?</span>'),
			],
			'name',
			'subscription_active',
			'subscription_expires',
			'user_limit',
			'notes:ntext',
			'admit_by_domain',
			'domain',
		],
	]); ?>


    <hr/>

    <?php echo Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('backend', 'Delete'), ['delete', 'id' => $model->id],
	[
		'class' => 'btn btn-danger',
		'data-confirm' => '' . Yii::t('backend', 'Are you sure to delete this item?') . '',
		'data-method' => 'post',
	]); ?>
    <?php $this->endBlock(); ?>



<?php $this->beginBlock('AeExtMregisterCompaniesUsers'); ?>
<div style='position: relative'>
<div style='position:absolute; right: 0px; top: 0px;'>
  <?php echo Html::a(
	'<span class="glyphicon glyphicon-list"></span> ' . Yii::t('backend', 'List All') . ' Company Employees',
	['/registration/ae-ext-mregister-companies-user/index'],
	['class'=>'btn text-muted btn-xs']
) ?>
  <?php echo Html::a(
	'<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('backend', 'New') . ' Company Employees',
	['/registration/ae-ext-mregister-companies-user/create', 'AeExtMregisterCompaniesUser' => ['company_id' => $model->id]],
	['class'=>'btn btn-success btn-xs']
); ?>
</div>
</div>
<?php Pjax::begin(['id'=>'pjax-AeExtMregisterCompaniesUsers', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-AeExtMregisterCompaniesUsers ul.pagination a, th a']) ?>
<?php echo
'<div class="table-responsive">'
	. \yii\grid\GridView::widget([
		'layout' => '{summary}{pager}<br/>{items}{pager}',
		'dataProvider' => new \yii\data\ActiveDataProvider([
				'query' => $model->getAeExtMregisterCompaniesUsers(),
				'pagination' => [
					'pageSize' => 20,
					'pageParam'=>'page-aeextmregistercompaniesusers',
				]
			]),
		'pager'        => [
			'class'          => yii\widgets\LinkPager::className(),
			'firstPageLabel' => Yii::t('backend', 'First'),
			'lastPageLabel'  => Yii::t('backend', 'Last')
		],
		'columns' => [
			[
				'class'      => 'yii\grid\ActionColumn',
				'template'   => '{view} {update}',
				'contentOptions' => ['nowrap'=>'nowrap'],
				'urlCreator' => function ($action, $model, $key, $index) {
					// using the column name as key, not mapping to 'id' like the standard generator
					$params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
					$params[0] = '/registration/ae-ext-mregister-companies-user' . '/' . $action;
					$params['AeExtMregisterCompaniesUser'] = ['company_id' => $model->primaryKey()[0]];
					return $params;
				},
				'buttons'    => [

				],
				'controller' => '/registration/ae-ext-mregister-companies-user'
			],
			'id',
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
			[
				'class' => yii\grid\DataColumn::className(),
				'attribute' => 'app_id',
				'value' => function ($model) {
					if ($rel = $model->app) {
						return Html::a($rel->name, ['/registration/ae-game/view', 'id' => $rel->id, ], ['data-pjax' => 0]);
					} else {
						return '';
					}
				},
				'format' => 'raw',
			],
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
			[
				'class' => yii\grid\DataColumn::className(),
				'attribute' => 'play_id',
				'value' => function ($model) {
					if ($rel = $model->play) {
						return Html::a($rel->id, ['/registration/ae-game-play/view', 'id' => $rel->id, ], ['data-pjax' => 0]);
					} else {
						return '';
					}
				},
				'format' => 'raw',
			],
			'registered',
			'firstname',
			'lastname',
			'department',
			'email:email',
			'phone',
		]
	])
	. '</div>'
?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?php echo Tabs::widget(
	[
		'id' => 'relation-tabs',
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => '<b class=""># '.Html::encode($model->id).'</b>',
				'content' => $this->blocks['backend\modules\registration\models\AeExtMregisterCompany'],
				'active'  => true,
			],
			[
				'content' => $this->blocks['AeExtMregisterCompaniesUsers'],
				'label'   => '<small>Company Employees <span class="badge badge-default">'. $model->getAeExtMregisterCompaniesUsers()->count() . '</span></small>',
				'active'  => false,
			],
		]
	]
);
?>
</div>
