<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var backend\modules\tickers\models\AeGame $model
*/
$copyParams = $model->attributes;

$this->title = Yii::t('backend', 'Ae Game');
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Ae Games'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('backend', 'View');
?>
<div class="giiant-crud ae-game-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?= Yii::t('backend', 'Ae Game') ?>
        <small>
            <?= $model->name ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
            '<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('backend', 'Edit'),
            [ 'update', 'id' => $model->id],
            ['class' => 'btn btn-info']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-copy"></span> ' . Yii::t('backend', 'Copy'),
            ['create', 'id' => $model->id, 'AeGame'=>$copyParams],
            ['class' => 'btn btn-success']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('backend', 'New'),
            ['create'],
            ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
            . Yii::t('backend', 'Full list'), ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr />

    <?php $this->beginBlock('backend\modules\tickers\models\AeGame'); ?>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'user_id',
    'value' => ($model->getUser()->one() ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['/tickers/usergroups-user/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->getUser()->one()->id, ['/tickers/usergroups-user/view', 'id' => $model->getUser()->one()->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'AeGame'=>['user_id' => $model->user_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'category_id',
    'value' => ($model->getCategory()->one() ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['/tickers/ae-category/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->getCategory()->one()->name, ['/tickers/ae-category/view', 'id' => $model->getCategory()->one()->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'AeGame'=>['category_id' => $model->category_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
        'active',
        'timelimit:datetime',
        'levels',
        'featured',
        'max_actions',
        'show_toplist',
        'register_email:email',
        'register_sms',
        'start_without_registration',
        'show_homepage',
        'choose_playername',
        'choose_avatar',
        'notifyme',
        'show_logo',
        'show_social',
        'custom_colors',
        'show_branches',
        'api_enabled',
        'keen_api_enabled',
        'google_api_enabled',
        'fb_api_enabled',
        'fb_invite_points',
        'hide_points',
        'nickname_variable_id',
        'show_toplist_points',
        'show_toplist_entries',
        'profilepic_variable_id',
        'notifications_enabled',
        'cookie_lifetime:datetime',
        'perm_can_reset',
        'perm_can_delete',
        'lang_show',
        'secondary_points',
        'tertiary_points',
        'template',
        'game_wide',
        'asset_migration',
        'background_image_landscape',
        'background_image_portrait',
        'logo',
        'length',
        'description:ntext',
        'alert',
        'custom_css',
        'shorturl:url',
        'custom_domain',
        'home_instructions:ntext',
        'social_share_url:url',
        'social_share_description',
        'social_force_to_canvas_url:url',
        'app_fb_hash',
        'colors:ntext',
        'api_key',
        'api_secret_key',
        'api_callback_url:url',
        'api_application_id',
        'keen_api_master_key',
        'keen_api_write_key:ntext',
        'keen_api_read_key:ntext',
        'keen_api_config:ntext',
        'google_api_code',
        'google_api_config:ntext',
        'fb_api_id',
        'fb_api_secret',
        'game_password',
        'notification_config:ntext',
        'secondary_points_title',
        'tertiary_points_title',
        'primary_points_shortname',
        'primary_points_title',
        'secondary_points_shortname',
        'tertiary_points_shortname',
        'thirdparty_api_config:ntext',
        'auth_config:ntext',
        'visual_config:ntext',
        'visual_config_params:ntext',
        'last_update',
        'name',
        'icon',
        'headboard_portrait',
        'headboard_landscape',
        'skin',
        'icon_primary_points',
        'icon_secondary_points',
        'icon_tertiary_points',
        'lang_default',
    ],
    ]); ?>

    
    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('backend', 'Delete'), ['delete', 'id' => $model->id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . Yii::t('backend', 'Are you sure to delete this item?') . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
<?php $this->beginBlock('AeGamePlays'); ?>
<div style='position: relative'>
<div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('backend', 'List All') . ' Ae Game Plays',
            ['/tickers/ae-game-play/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('backend', 'New') . ' Ae Game Play',
            ['/tickers/ae-game-play/create', 'AeGamePlay' => ['game_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div>
</div>
<?php Pjax::begin(['id'=>'pjax-AeGamePlays', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-AeGamePlays ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?=
 '<div class="table-responsive">'
 . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider([
        'query' => $model->getAeGamePlays(),
        'pagination' => [
            'pageSize' => 20,
            'pageParam'=>'page-aegameplays',
        ]
    ]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('backend', 'First'),
        'lastPageLabel'  => Yii::t('backend', 'Last')
    ],
    'columns' => [
 [
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = '/tickers/ae-game-play' . '/' . $action;
        $params['AeGamePlay'] = ['game_id' => $model->primaryKey()[0]];
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => '/tickers/ae-game-play'
],
        'id',
        'role_id',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'user_id',
    'value' => function ($model) {
        if ($rel = $model->getUser()->one()) {
            return Html::a($rel->id, ['/tickers/usergroups-user/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
        'last_update',
        'created',
        'progress',
        'status',
        'alert',
        'level',
]
])
 . '</div>' 
?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [
 [
    'label'   => '<b class=""># '.$model->id.'</b>',
    'content' => $this->blocks['backend\modules\tickers\models\AeGame'],
    'active'  => true,
],
[
    'content' => $this->blocks['AeGamePlays'],
    'label'   => '<small>Ae Game Plays <span class="badge badge-default">'.count($model->getAeGamePlays()->asArray()->all()).'</span></small>',
    'active'  => false,
],
 ]
                 ]
    );
    ?>
</div>
