<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\fitness\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_fit_pr".
 *
 * @property string $id
 * @property string $app_id
 * @property string $title
 * @property string $unit
 *
 * @property \backend\modules\fitness\models\AeExtFitComponentMovement[] $aeExtFitComponentMovements
 * @property \backend\modules\fitness\models\AeGame $app
 * @property \backend\modules\fitness\models\AeExtFitPrUser[] $aeExtFitPrUsers
 * @property string $aliasModel
 */
abstract class AeExtFitPr extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_fit_pr';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['app_id', 'title', 'unit'], 'required'],
            [['app_id'], 'integer'],
            [['title', 'unit'], 'string', 'max' => 255],
            [['app_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\fitness\models\AeGame::className(), 'targetAttribute' => ['app_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'app_id' => Yii::t('backend', 'App ID'),
            'title' => Yii::t('backend', 'Title'),
            'unit' => Yii::t('backend', 'Unit'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAeExtFitComponentMovements()
    {
        return $this->hasMany(\backend\modules\fitness\models\AeExtFitComponentMovement::className(), ['pr_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getApp()
    {
        return $this->hasOne(\backend\modules\fitness\models\AeGame::className(), ['id' => 'app_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAeExtFitPrUsers()
    {
        return $this->hasMany(\backend\modules\fitness\models\AeExtFitPrUser::className(), ['pr_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\fitness\models\query\AeExtFitPrQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\fitness\models\query\AeExtFitPrQuery(get_called_class());
    }


}
