<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\fitness\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_fit_program_exercise".
 *
 * @property string $id
 * @property string $program_id
 * @property string $exercise_id
 * @property integer $week
 * @property integer $day
 * @property integer $priority
 * @property string $time
 * @property string $repeat_days
 *
 * @property \backend\modules\fitness\models\AeExtFitExercise $exercise
 * @property \backend\modules\fitness\models\AeExtFitProgram $program
 * @property string $aliasModel
 */
abstract class AeExtFitProgramExercise extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_fit_program_exercise';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['program_id', 'exercise_id'], 'required'],
            [['program_id', 'exercise_id', 'week', 'day', 'priority'], 'integer'],
            [['time', 'repeat_days'], 'string', 'max' => 255],
            [['exercise_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\fitness\models\AeExtFitExercise::className(), 'targetAttribute' => ['exercise_id' => 'id']],
            [['program_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\fitness\models\AeExtFitProgram::className(), 'targetAttribute' => ['program_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'program_id' => Yii::t('backend', 'Program ID'),
            'exercise_id' => Yii::t('backend', 'Exercise ID'),
            'week' => Yii::t('backend', 'Week'),
            'day' => Yii::t('backend', 'Day'),
            'priority' => Yii::t('backend', 'Priority'),
            'time' => Yii::t('backend', 'Time'),
            'repeat_days' => Yii::t('backend', 'Repeat Days'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getExercise()
    {
        return $this->hasOne(\backend\modules\fitness\models\AeExtFitExercise::className(), ['id' => 'exercise_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProgram()
    {
        return $this->hasOne(\backend\modules\fitness\models\AeExtFitProgram::className(), ['id' => 'program_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\fitness\models\query\AeExtFitProgramExerciseQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\fitness\models\query\AeExtFitProgramExerciseQuery(get_called_class());
    }


}
