<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\fitness\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_purchase_product".
 *
 * @property integer $id
 * @property integer $app_id
 * @property string $name
 * @property string $code
 * @property string $type
 * @property string $price
 * @property string $currency
 * @property string $code_ios
 * @property string $code_android
 * @property string $description
 * @property string $image
 * @property string $icon
 *
 * @property \backend\modules\fitness\models\AeExtPurchase[] $aeExtPurchases
 * @property \backend\modules\fitness\models\AeGame $app
 * @property string $aliasModel
 */
abstract class AeExtPurchaseProduct extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_purchase_product';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['app_id', 'name', 'code', 'type', 'price', 'currency', 'code_ios', 'code_android', 'description', 'image', 'icon'], 'required'],
            [['app_id'], 'integer'],
            [['price'], 'decimal'],
            [['description'], 'string'],
            [['name', 'code', 'type', 'code_ios', 'code_android', 'image', 'icon'], 'string', 'max' => 255],
            [['currency'], 'string', 'max' => 5],
            [['app_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\fitness\models\AeGame::className(), 'targetAttribute' => ['app_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'app_id' => Yii::t('backend', 'App ID'),
            'name' => Yii::t('backend', 'Name'),
            'code' => Yii::t('backend', 'Code'),
            'type' => Yii::t('backend', 'Type'),
            'price' => Yii::t('backend', 'Price'),
            'currency' => Yii::t('backend', 'Currency'),
            'code_ios' => Yii::t('backend', 'Code Ios'),
            'code_android' => Yii::t('backend', 'Code Android'),
            'description' => Yii::t('backend', 'Description'),
            'image' => Yii::t('backend', 'Image'),
            'icon' => Yii::t('backend', 'Icon'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAeExtPurchases()
    {
        return $this->hasMany(\backend\modules\fitness\models\AeExtPurchase::className(), ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getApp()
    {
        return $this->hasOne(\backend\modules\fitness\models\AeGame::className(), ['id' => 'app_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\fitness\models\query\AeExtPurchaseProductQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\fitness\models\query\AeExtPurchaseProductQuery(get_called_class());
    }


}
