<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\fitness\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_fit_program_category".
 *
 * @property string $id
 * @property string $app_id
 * @property string $name
 * @property string $icon
 * @property string $color
 * @property integer $category_order
 *
 * @property \backend\modules\fitness\models\AeExtFitProgram[] $aeExtFitPrograms
 * @property \backend\modules\fitness\models\AeGame $app
 * @property string $aliasModel
 */
abstract class AeExtFitProgramCategory extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_fit_program_category';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['app_id', 'name', 'color'], 'required'],
            [['app_id', 'category_order'], 'integer'],
            [['name', 'icon'], 'string', 'max' => 255],
            [['color'], 'string', 'max' => 7],
            [['app_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\fitness\models\AeGame::className(), 'targetAttribute' => ['app_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'app_id' => Yii::t('backend', 'App ID'),
            'name' => Yii::t('backend', 'Name'),
            'icon' => Yii::t('backend', 'Icon'),
            'color' => Yii::t('backend', 'Color'),
            'category_order' => Yii::t('backend', 'Category Order'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAeExtFitPrograms()
    {
        return $this->hasMany(\backend\modules\fitness\models\AeExtFitProgram::className(), ['category_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getApp()
    {
        return $this->hasOne(\backend\modules\fitness\models\AeGame::className(), ['id' => 'app_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\fitness\models\query\AeExtFitProgramCategoryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\fitness\models\query\AeExtFitProgramCategoryQuery(get_called_class());
    }


}
