<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\fitness\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_fit_program_recipe".
 *
 * @property string $id
 * @property string $program_id
 * @property string $recipe_id
 * @property integer $recipe_order
 * @property integer $week
 *
 * @property \backend\modules\fitness\models\AeExtFitProgram $program
 * @property \backend\modules\fitness\models\AeExtFoodRecipe $recipe
 * @property string $aliasModel
 */
abstract class AeExtFitProgramRecipe extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_fit_program_recipe';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['program_id', 'recipe_id', 'recipe_order','week'], 'required'],
            [['program_id', 'recipe_id', 'recipe_order','week'], 'integer'],
            [['program_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\fitness\models\AeExtFitProgram::className(), 'targetAttribute' => ['program_id' => 'id']],
            [['recipe_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\fitness\models\AeExtFoodRecipe::className(), 'targetAttribute' => ['recipe_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'program_id' => Yii::t('backend', 'Program ID'),
            'recipe_id' => Yii::t('backend', 'Recipe ID'),
            'recipe_order' => Yii::t('backend', 'Recipe Order'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProgram()
    {
        return $this->hasOne(\backend\modules\fitness\models\AeExtFitProgram::className(), ['id' => 'program_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRecipe()
    {
        return $this->hasOne(\backend\modules\fitness\models\AeExtFoodRecipe::className(), ['id' => 'recipe_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\fitness\models\query\AeExtFitProgramRecipeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\fitness\models\query\AeExtFitProgramRecipeQuery(get_called_class());
    }


}
