<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\fitness\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_fit_movement_category".
 *
 * @property string $id
 * @property string $name
 * @property string $admin_name
 * @property string $timer_type
 * @property string $rounds
 * @property string $background_image
 *
 * @property \backend\modules\fitness\models\AeExtFitExerciseMovementCategory[] $aeExtFitExerciseMovementCategories
 * @property string $aliasModel
 */
abstract class AeExtFitMovementCategory extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_fit_movement_category';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name','admin_name', 'timer_type'], 'required'],
            [['rounds'], 'integer'],
            [['name','admin_name', 'timer_type', 'background_image'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'name' => Yii::t('backend', 'Name'),
            'timer_type' => Yii::t('backend', 'Timer Type'),
            'rounds' => Yii::t('backend', 'Rounds'),
            'background_image' => Yii::t('backend', 'Background Image'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAeExtFitExerciseMovementCategories()
    {
        return $this->hasMany(\backend\modules\fitness\models\AeExtFitExerciseMovementCategory::className(), ['movement_category' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\fitness\models\query\AeExtFitMovementCategoryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\fitness\models\query\AeExtFitMovementCategoryQuery(get_called_class());
    }


}
