<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\fitness\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_fit_program".
 *
 * @property string $id
 * @property string $app_id
 * @property string $name
 * @property string $category_id
 * @property string $subcategory_id
 * @property string $article_id
 * @property string $program_type
 * @property string $program_sub_type
 * @property integer $is_challenge
 * @property integer $exercises_per_day
 *
 * @property \backend\modules\fitness\models\AeExtCalendarEntry[] $aeExtCalendarEntries
 * @property \backend\modules\fitness\models\AeGame $app
 * @property \backend\modules\fitness\models\AeExtArticle $article
 * @property \backend\modules\fitness\models\AeExtFitProgramCategory $category
 * @property \backend\modules\fitness\models\AeExtFitProgramSubcategory $subcategory
 * @property \backend\modules\fitness\models\AeExtFitProgramExercise[] $aeExtFitProgramExercises
 * @property \backend\modules\fitness\models\AeExtFitProgramRecipe[] $aeExtFitProgramRecipes
 * @property \backend\modules\fitness\models\AeExtFitProgramSelection[] $aeExtFitProgramSelections
 * @property string $aliasModel
 */
abstract class AeExtFitProgram extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_fit_program';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['app_id', 'name', 'program_type', 'program_sub_type'], 'required'],
            [['app_id', 'category_id', 'subcategory_id', 'article_id', 'is_challenge', 'exercises_per_day'], 'integer'],
            [['name', 'program_type', 'program_sub_type'], 'string', 'max' => 255],
            [['app_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\fitness\models\AeGame::className(), 'targetAttribute' => ['app_id' => 'id']],
            [['article_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\fitness\models\AeExtArticle::className(), 'targetAttribute' => ['article_id' => 'id']],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\fitness\models\AeExtFitProgramCategory::className(), 'targetAttribute' => ['category_id' => 'id']],
            [['subcategory_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\fitness\models\AeExtFitProgramSubcategory::className(), 'targetAttribute' => ['subcategory_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'app_id' => Yii::t('backend', 'App ID'),
            'name' => Yii::t('backend', 'Name'),
            'category_id' => Yii::t('backend', 'Category ID'),
            'subcategory_id' => Yii::t('backend', 'Subcategory ID'),
            'article_id' => Yii::t('backend', 'Article ID'),
            'program_type' => Yii::t('backend', 'Program Type'),
            'program_sub_type' => Yii::t('backend', 'Program Sub Type'),
            'is_challenge' => Yii::t('backend', 'Is Challenge'),
            'exercises_per_day' => Yii::t('backend', 'Exercises Per Day'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAeExtCalendarEntries()
    {
        return $this->hasMany(\backend\modules\fitness\models\AeExtCalendarEntry::className(), ['program_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getApp()
    {
        return $this->hasOne(\backend\modules\fitness\models\AeGame::className(), ['id' => 'app_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticle()
    {
        return $this->hasOne(\backend\modules\fitness\models\AeExtArticle::className(), ['id' => 'article_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(\backend\modules\fitness\models\AeExtFitProgramCategory::className(), ['id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubcategory()
    {
        return $this->hasOne(\backend\modules\fitness\models\AeExtFitProgramSubcategory::className(), ['id' => 'subcategory_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAeExtFitProgramExercises()
    {
        return $this->hasMany(\backend\modules\fitness\models\AeExtFitProgramExercise::className(), ['program_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAeExtFitProgramRecipes()
    {
        return $this->hasMany(\backend\modules\fitness\models\AeExtFitProgramRecipe::className(), ['program_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAeExtFitProgramSelections()
    {
        return $this->hasMany(\backend\modules\fitness\models\AeExtFitProgramSelection::className(), ['program_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\fitness\models\query\AeExtFitProgramQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\fitness\models\query\AeExtFitProgramQuery(get_called_class());
    }


}
