<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\fitness\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_food_recipe_ingredient".
 *
 * @property integer $id
 * @property string $recipe_id
 * @property integer $ingredient_id
 * @property integer $quantity
 *
 * @property \backend\modules\fitness\models\AeExtFoodIngredient $ingredient
 * @property \backend\modules\fitness\models\AeExtFoodRecipe $recipe
 * @property string $aliasModel
 */
abstract class AeExtFoodRecipeIngredient extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_food_recipe_ingredient';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['recipe_id', 'ingredient_id', 'quantity'], 'required'],
            [['recipe_id', 'ingredient_id', 'quantity'], 'integer'],
            [['ingredient_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\fitness\models\AeExtFoodIngredient::className(), 'targetAttribute' => ['ingredient_id' => 'id']],
            [['recipe_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\fitness\models\AeExtFoodRecipe::className(), 'targetAttribute' => ['recipe_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'recipe_id' => Yii::t('backend', 'Recipe ID'),
            'ingredient_id' => Yii::t('backend', 'Ingredient ID'),
            'quantity' => Yii::t('backend', 'Quantity'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIngredient()
    {
        return $this->hasOne(\backend\modules\fitness\models\AeExtFoodIngredient::className(), ['id' => 'ingredient_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRecipe()
    {
        return $this->hasOne(\backend\modules\fitness\models\AeExtFoodRecipe::className(), ['id' => 'recipe_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\fitness\models\query\AeExtFoodRecipeIngredientQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\fitness\models\query\AeExtFoodRecipeIngredientQuery(get_called_class());
    }


}
