<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\fitness\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_purchase".
 *
 * @property integer $id
 * @property integer $app_id
 * @property integer $play_id
 * @property integer $product_id
 * @property integer $price
 * @property string $currency
 * @property string $type
 * @property string $date
 * @property string $store_id
 * @property string $receipt
 * @property string $subject
 * @property integer $subscription
 * @property integer $yearly
 * @property integer $monthly
 * @property integer $expiry
 * @property string $email
 *
 * @property \backend\modules\fitness\models\AeGame $app
 * @property \backend\modules\fitness\models\AeGamePlay $play
 * @property \backend\modules\fitness\models\AeExtPurchaseProduct $product
 * @property string $aliasModel
 */
abstract class AeExtPurchase extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_purchase';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['app_id', 'play_id', 'product_id', 'price', 'currency', 'type', 'date', 'store_id', 'receipt', 'subject', 'subscription', 'yearly', 'monthly', 'expiry', 'email'], 'required'],
            [['app_id', 'play_id', 'product_id', 'price', 'subscription', 'yearly', 'monthly', 'expiry'], 'integer'],
            [['date'], 'safe'],
            [['receipt'], 'string'],
            [['currency'], 'string', 'max' => 5],
            [['type', 'store_id', 'subject', 'email'], 'string', 'max' => 255],
            [['app_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\fitness\models\AeGame::className(), 'targetAttribute' => ['app_id' => 'id']],
            [['play_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\fitness\models\AeGamePlay::className(), 'targetAttribute' => ['play_id' => 'id']],
            [['product_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\fitness\models\AeExtPurchaseProduct::className(), 'targetAttribute' => ['product_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'app_id' => Yii::t('backend', 'App ID'),
            'play_id' => Yii::t('backend', 'Play ID'),
            'product_id' => Yii::t('backend', 'Product ID'),
            'price' => Yii::t('backend', 'Price'),
            'currency' => Yii::t('backend', 'Currency'),
            'type' => Yii::t('backend', 'Type'),
            'date' => Yii::t('backend', 'Date'),
            'store_id' => Yii::t('backend', 'Store ID'),
            'receipt' => Yii::t('backend', 'Receipt'),
            'subject' => Yii::t('backend', 'Subject'),
            'subscription' => Yii::t('backend', 'Subscription'),
            'yearly' => Yii::t('backend', 'Yearly'),
            'monthly' => Yii::t('backend', 'Monthly'),
            'expiry' => Yii::t('backend', 'Expiry'),
            'email' => Yii::t('backend', 'Email'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getApp()
    {
        return $this->hasOne(\backend\modules\fitness\models\AeGame::className(), ['id' => 'app_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlay()
    {
        return $this->hasOne(\backend\modules\fitness\models\AeGamePlay::className(), ['id' => 'play_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduct()
    {
        return $this->hasOne(\backend\modules\fitness\models\AeExtPurchaseProduct::className(), ['id' => 'product_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\fitness\models\query\AeExtPurchaseQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\fitness\models\query\AeExtPurchaseQuery(get_called_class());
    }


}
