<?php
/**
 * /Users/trailo/dev/aecore/app/appzioUI/console/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 *
 * @var yii\web\View $this
 * @var backend\modules\fitness\models\AeExtPurchase $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="ae-ext-purchase-form">

    <?php $form = ActiveForm::begin([
		'id' => 'AeExtPurchase',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-danger',
		'fieldConfig' => [
			'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
			'horizontalCssClasses' => [
				'label' => 'col-sm-2',
				//'offset' => 'col-sm-offset-4',
				'wrapper' => 'col-sm-8',
				'error' => '',
				'hint' => '',
			],
		],
	]
);
?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


<!-- attribute app_id -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'app_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(backend\modules\fitness\models\AeGame::find()->all(), 'id', 'name'),
	[
		'prompt' => Yii::t('backend', 'Select'),
		'disabled' => (isset($relAttributes) && isset($relAttributes['app_id'])),
	]
); ?>

<!-- attribute play_id -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'play_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(backend\modules\fitness\models\AeGamePlay::find()->all(), 'id', 'id'),
	[
		'prompt' => Yii::t('backend', 'Select'),
		'disabled' => (isset($relAttributes) && isset($relAttributes['play_id'])),
	]
); ?>

<!-- attribute product_id -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'product_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(backend\modules\fitness\models\AeExtPurchaseProduct::find()->all(), 'id', 'name'),
	[
		'prompt' => Yii::t('backend', 'Select'),
		'disabled' => (isset($relAttributes) && isset($relAttributes['product_id'])),
	]
); ?>

<!-- attribute price -->
			<?php echo $form->field($model, 'price')->textInput() ?>

<!-- attribute currency -->
			<?php echo $form->field($model, 'currency')->textInput(['maxlength' => true]) ?>

<!-- attribute type -->
			<?php echo $form->field($model, 'type')->textInput(['maxlength' => true]) ?>

<!-- attribute date -->
			<?php echo $form->field($model, 'date')->textInput() ?>

<!-- attribute store_id -->
			<?php echo $form->field($model, 'store_id')->textInput(['maxlength' => true]) ?>

<!-- attribute receipt -->
			<?php echo $form->field($model, 'receipt')->textarea(['rows' => 6]) ?>

<!-- attribute subject -->
			<?php echo $form->field($model, 'subject')->textInput(['maxlength' => true]) ?>

<!-- attribute subscription -->
			<?php echo $form->field($model, 'subscription')->textInput() ?>

<!-- attribute expiry -->
			<?php echo $form->field($model, 'expiry')->textInput() ?>

<!-- attribute email -->
			<?php echo $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
        </p>
        <?php $this->endBlock(); ?>

        <?php echo
Tabs::widget(
	[
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => Yii::t('backend', 'AeExtPurchase'),
				'content' => $this->blocks['main'],
				'active'  => true,
			],
		]
	]
);
?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?php echo Html::submitButton(
	'<span class="glyphicon glyphicon-check"></span> ' .
	($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Save')),
	[
		'id' => 'save-' . $model->formName(),
		'class' => 'btn btn-success'
	]
);
?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
