<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\articles\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_article_bookmarks".
 *
 * @property string $id
 * @property string $play_id
 * @property string $article_id
 * @property string $type
 *
 * @property \backend\modules\articles\models\AeGamePlay $play
 * @property \backend\modules\articles\models\AeExtArticle $article
 * @property string $aliasModel
 */
abstract class AeExtArticleBookmark extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_article_bookmarks';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['play_id', 'article_id'], 'required'],
            [['play_id', 'article_id'], 'integer'],
            [['type'], 'string', 'max' => 255],
            [['play_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\articles\models\AeGamePlay::className(), 'targetAttribute' => ['play_id' => 'id']],
            [['article_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\articles\models\AeExtArticle::className(), 'targetAttribute' => ['article_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'play_id' => Yii::t('backend', 'Play ID'),
            'article_id' => Yii::t('backend', 'Article ID'),
            'type' => Yii::t('backend', 'Type'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlay()
    {
        return $this->hasOne(\backend\modules\articles\models\AeGamePlay::className(), ['id' => 'play_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticle()
    {
        return $this->hasOne(\backend\modules\articles\models\AeExtArticle::className(), ['id' => 'article_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\articles\models\query\AeExtArticleBookmarkQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\articles\models\query\AeExtArticleBookmarkQuery(get_called_class());
    }


}
