<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 * @var yii\web\View $this
 * @var backend\modules\fitness\models\AeExtFitProgram $model
 * @var yii\widgets\ActiveForm $form
 * @var $weeks
 * @var $exercise
 * @var $recipes
 * @var $exercise_json
 * @var $recipes_json
 */

$operator = '<>';
$show_challenge_field = true;

if (
    (isset($_GET['cat']) AND $_GET['cat'] == 'food') OR
    $model->program_type == 'food'
) {
    $operator = 'LIKE';
    $show_challenge_field = false;
}

?>

<div class="ae-ext-fit-program-form">

    <?php $form = ActiveForm::begin([
            'id' => 'AeExtFitProgram',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-danger',
            'fieldConfig' => [
                'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
                'horizontalCssClasses' => [
                    'label' => 'col-sm-2',
                    #'offset' => 'col-sm-offset-4',
                    'wrapper' => 'col-sm-8',
                    'error' => '',
                    'hint' => '',
                ],
            ],
        ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>

            <!-- attribute app_id -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'app_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(backend\modules\fitness\models\AeGame::find()->all(), 'id', 'name'),
                [
                    'prompt' => Yii::t('backend', 'Select'),
                    'disabled' => ($model->app_id ? true : false),
                ]
            ); ?>

            <!-- attribute name -->
            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

            <!-- attribute category_id -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'category_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(backend\modules\fitness\models\AeExtFitProgramCategory::find()->where([$operator, 'name', 'Nutrition'])->all(), 'id', 'name'),
                [
                    'prompt' => Yii::t('backend', 'Select'),
                    'disabled' => ($model->category_id AND $model->program_type == 'food' || $model->program_type == 'mindfulness'? true : false),
                ]
            ); ?>

            <!-- attribute subcategory_id -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'subcategory_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(backend\modules\fitness\models\AeExtFitProgramSubcategory::findAll([
                        'type' => ($model->program_type == 'food' ? 'food' : 'fitness')
                ]), 'id', 'name'),
                [
                    'prompt' => Yii::t('backend', 'Select'),
                    'disabled' => (isset($relAttributes) && isset($relAttributes['subcategory_id'])),
                ]
            ); ?>

            <!-- attribute article_id -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'article_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(backend\modules\fitness\models\AeExtArticle::find()->all(), 'id', 'title'),
                [
                    'prompt' => Yii::t('backend', 'Select'),
                    'disabled' => (isset($relAttributes) && isset($relAttributes['article_id'])),
                ]
            ); ?>


            <!-- attribute name -->


                <!-- attribute exercises_per_day -->
                <?= $form->field($model, 'exercises_per_day')->dropDownList([
                        '1' => '1',
                        '2' => '2',
                        '3' => '3',
                        '4' => '4',
                ]) ?>

            <?php if ($show_challenge_field):?>

                <?= $form->field($model, 'is_challenge')->checkbox([], false); ?>

            <?php endif;?>

            <?php if($weeks):?>

                <?= Yii::$app->controller->renderPartial('weeks_tabs', [
                    'weeks' => $weeks,
                    'exercise' => $exercise,
                    'recipes' => $recipes,
                    'exercise_json' => $exercise_json,
                    'items_per_day' => $model->exercises_per_day,
                    'recipes_json' => $recipes_json
                ]); ?>

            <?php else: ?>

                <?= Yii::$app->controller->renderPartial('default-exercises-repeater', [
                    'exercise'=>$exercise,
                    'exercise_json' => $exercise_json
                ]); ?>

            <?php endif;?>
        </p>
        <?php $this->endBlock(); ?>

        <?=
        Tabs::widget(
            [
                'encodeLabels' => false,
                'items' => [
                    [
                        'label' => Yii::t('backend', 'Program'),
                        'content' => $this->blocks['main'],
                        'active' => true,
                    ],
                ]
            ]
        );
        ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Save')),
            [
                'id' => 'save-' . $model->formName(),
                'class' => 'btn btn-success'
            ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>