<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\users\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_game_play_variable".
 *
 * @property string $id
 * @property string $play_id
 * @property string $variable_id
 * @property string $name
 * @property string $value
 * @property string $parameters
 * @property string $aliasModel
 */
abstract class AeGamePlayVariable extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_game_play_variable';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['play_id', 'variable_id'], 'integer'],
            [['variable_id', 'name', 'value', 'parameters'], 'required'],
            [['value', 'parameters'], 'string'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'play_id' => Yii::t('backend', 'Play ID'),
            'variable_id' => Yii::t('backend', 'Variable ID'),
            'name' => Yii::t('backend', 'Name'),
            'value' => Yii::t('backend', 'Value'),
            'parameters' => Yii::t('backend', 'Parameters'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\users\models\query\AeGamePlayVariableQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\users\models\query\AeGamePlayVariableQuery(get_called_class());
    }


}
