<?php

use backend\components\Helper;
use dmstr\bootstrap\Tabs;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var backend\modules\items\models\AeExtItem $model
 * @var yii\widgets\ActiveForm $form
 * @var $allowed_fields
 * @var $images_json
 * @var $categories
 * @var $categories_json
 */

?>

<div class="ae-ext-item-form">

    <?php $form = ActiveForm::begin([
            'id' => 'AeExtItem',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-danger',
            'fieldConfig' => [
                'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
                'horizontalCssClasses' => [
                    'label' => 'col-sm-2',
                    #'offset' => 'col-sm-offset-4',
                    'wrapper' => 'col-sm-8',
                    'error' => '',
                    'hint' => '',
                ],
            ],
        ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            <!-- attribute play_id -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'play_id', [
                'options' => [
                    'class' => Helper::getFieldClass('play_id', $allowed_fields),
                ]
            ])->dropDownList(
                \yii\helpers\ArrayHelper::map(backend\modules\items\models\AeGamePlay::find()->all(), 'id', 'id'),
                [
                    'prompt' => Yii::t('backend', 'Select'),
                    'disabled' => (isset($relAttributes) && isset($relAttributes['play_id'])),
                ]
            ); ?>

            <!-- attribute game_id -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'game_id', [
                'options' => [
                    'class' => Helper::getFieldClass('game_id', $allowed_fields),
                ]
            ])->dropDownList(
                \yii\helpers\ArrayHelper::map(backend\modules\items\models\AeGame::find()->all(), 'id', 'name'),
                [
                    'prompt' => Yii::t('backend', 'Select'),
                    'disabled' => (isset($relAttributes) && isset($relAttributes['game_id'])),
                ]
            )->label('Application'); ?>

            <!-- attribute category_id -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'category_id', [
                'options' => [
                    'class' => Helper::getFieldClass('category_id', $allowed_fields),
                ]
            ])->dropDownList(
                \yii\helpers\ArrayHelper::map(backend\modules\items\models\AeExtItemsCategory::find()->all(), 'id', 'name'),
                [
                    'prompt' => Yii::t('backend', 'Select'),
                    'disabled' => (isset($relAttributes) && isset($relAttributes['category_id'])),
                ]
            ); ?>

            <!-- attribute place_id -->


            <!-- attribute date_added -->
            <?= $form->field($model, 'date_added', [
                'options' => [
                    'class' => Helper::getFieldClass('date_added', $allowed_fields),
                ]
            ])->textInput() ?>

            <!-- attribute featured -->

            <!-- attribute importa_date -->

            <!-- attribute type -->
            <?= $form->field($model, 'type', [
                'options' => [
                    'class' => Helper::getFieldClass('type', $allowed_fields),
                ]
            ])->textInput([
                'maxlength' => true,
                'value' => 'event',
                'readonly' => true,
            ]) ?>

            <!-- attribute name -->
            <?= $form->field($model, 'name', [
                'options' => [
                    'class' => Helper::getFieldClass('name', $allowed_fields),
                ]
            ])->textInput(['maxlength' => true]) ?>


            <!-- attribute lat -->
            <?= $form->field($model, 'lat', [
                'options' => [
                    'class' => Helper::getFieldClass('lat', $allowed_fields),
                ]
            ])->textInput(['maxlength' => true]) ?>

            <!-- attribute lon -->
            <?= $form->field($model, 'lon', [
                'options' => [
                    'class' => Helper::getFieldClass('lon', $allowed_fields),
                ]
            ])->textInput(['maxlength' => true]) ?>

            <!-- attribute images -->
            <?= $form->field($model, 'images', [
                'options' => [
                    'class' => Helper::getFieldClass('images', $allowed_fields),
                ]
            ])->textarea(['rows' => 6]) ?>

            <!-- attribute extra_data -->

            <!-- attribute description -->
            <?= $form->field($model, 'description', [
                'options' => [
                    'class' => Helper::getFieldClass('description', $allowed_fields),
                ]
            ])->textarea(['rows' => 6]) ?>

            <!-- attribute time -->
            <?= $form->field($model, 'time', [
                'options' => [
                    'class' => Helper::getFieldClass('time', $allowed_fields),
                ]
            ])->textInput(['maxlength' => true]) ?>

            <!-- attribute status -->
            <?= $form->field($model, 'status', [
                'options' => [
                    'class' => Helper::getFieldClass('status', $allowed_fields),
                ]
            ])->textInput(['maxlength' => true]) ?>


        </p>

        <?= Yii::$app->controller->renderPartial('item-images', [
            'form' => $form,
            'model' => $model,
            'images_json' => $images_json,
        ]); ?>

        <?= Yii::$app->controller->renderPartial('item-categories', [
            'categories' => $categories,
            'categories_json' => $categories_json,
        ]); ?>

        <?php $this->endBlock(); ?>

        <?=
        Tabs::widget(
            [
                'encodeLabels' => false,
                'items' => [
                    [
                        'label' => Yii::t('backend', 'AeExtItem'),
                        'content' => $this->blocks['main'],
                        'active' => true,
                    ],
                ]
            ]
        );
        ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Save')),
            [
                'id' => 'save-' . $model->formName(),
                'class' => 'btn btn-success'
            ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>