<?php

use backend\components\Helper;
use dmstr\bootstrap\Tabs;
use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/**
 * @var yii\web\View $this
 * @var backend\modules\articles\models\AeExtArticle $model
 */
$copyParams = $model->attributes;

$this->title = Yii::t('backend', 'Article');
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Articles'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('backend', 'View');
?>
<div class="giiant-crud ae-ext-article-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?= Yii::t('backend', 'Article') ?>
        <small>
            <?= $model->title ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
                '<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('backend', 'Edit'),
                ['update', 'id' => $model->id],
                ['class' => 'btn btn-info']) ?>

            <?= Html::a(
                '<span class="glyphicon glyphicon-copy"></span> ' . Yii::t('backend', 'Copy'),
                ['create', 'id' => $model->id, 'exact-copy' => 1],
                [
                        'class' => 'btn btn-success',
                        'data' => [
                            'confirm' => Yii::t('backend', 'Are you sure you want to copy this article?'),
                        ],
                ]) ?>

            <?= Html::a(
                '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('backend', 'New'),
                ['create'],
                ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
                . Yii::t('backend', 'Full list'), ['index'], ['class' => 'btn btn-default']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('backend\modules\articles\models\AeExtArticle'); ?>


    <?= DetailView::widget([
        'model' => $model,
        'options' => ['class' => 'table table-striped table-bordered detail-view article-detail-view'],
        'attributes' => [
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'app_id',
                'value' => ($model->getApp()->one() ?
                    Html::a('<i class="glyphicon glyphicon-list"></i>', ['/articles/ae-game/index']) . ' ' .
                    Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> ' . $model->getApp()->one()->name, ['/articles/ae-game/view', 'id' => $model->getApp()->one()->id,]) . ' ' .
                    Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'AeExtArticle' => ['app_id' => $model->app_id]])
                    :
                    '<span class="label label-warning">?</span>'),
            ],
            'title',
            'header:ntext',
            // 'content:ntext',
            [
                'format' => 'html',
                'attribute' => 'content',
                'value' => Helper::getArticlePreview($model),
            ],
            'link:ntext',
            'rating',
            [
                'format' => 'html',
                'attribute' => 'category_id',
                'value' => ($model->getCategory()->one() ?
                    Html::a('<i class="glyphicon glyphicon-list"></i>', ['/articles/ae-ext-article-category/index']) . ' ' .
                    Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> ' . $model->getCategory()->one()->title, ['/articles/ae-ext-article-category/view', 'id' => $model->getCategory()->one()->id,]) . ' ' .
                    Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'AeExtArticle' => ['category_id' => $model->category_id]])
                    :
                    '<span class="label label-warning">?</span>'),
            ],
            [
                'format' => 'html',
                'attribute' => 'play_id',
                'value' => ($model->getPlay()->one() ?
                    Html::a('<i class="glyphicon glyphicon-list"></i>', ['/articles/ae-game-play/index']) . ' ' .
                    Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> ' . $model->getPlay()->one()->id, ['/articles/ae-game-play/view', 'id' => $model->getPlay()->one()->id,]) . ' ' .
                    Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'AeExtArticle' => ['play_id' => $model->play_id]])
                    :
                    '<span class="label label-warning">?</span>'),
            ],
            'featured',
            'article_date',
        ],
    ]); ?>


    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('backend', 'Delete'), ['delete', 'id' => $model->id],
        [
            'class' => 'btn btn-danger',
            'data-confirm' => '' . Yii::t('backend', 'Are you sure to delete this item?') . '',
            'data-method' => 'post',
        ]); ?>
    <?php $this->endBlock(); ?>



    <?php $this->beginBlock('AeExtArticleBookmarks'); ?>
    <div style='position: relative'>
        <div style='position:absolute; right: 0px; top: 0px;'>
            <?= Html::a(
                '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('backend', 'List All') . ' Article Bookmarks',
                ['/articles/ae-ext-article-bookmark/index'],
                ['class' => 'btn text-muted btn-xs']
            ) ?>
            <?= Html::a(
                '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('backend', 'New') . ' Article Bookmark',
                ['/articles/ae-ext-article-bookmark/create', 'AeExtArticleBookmark' => ['article_id' => $model->id]],
                ['class' => 'btn btn-success btn-xs']
            ); ?>
        </div>
    </div>
    <?php Pjax::begin(['id' => 'pjax-AeExtArticleBookmarks', 'enableReplaceState' => false, 'linkSelector' => '#pjax-AeExtArticleBookmarks ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>
    <?=
    '<div class="table-responsive">'
    . \yii\grid\GridView::widget([
        'layout' => '{summary}{pager}<br/>{items}{pager}',
        'dataProvider' => new \yii\data\ActiveDataProvider([
            'query' => $model->getAeExtArticleBookmarks(),
            'pagination' => [
                'pageSize' => 20,
                'pageParam' => 'page-aeextarticlebookmarks',
            ]
        ]),
        'pager' => [
            'class' => yii\widgets\LinkPager::className(),
            'firstPageLabel' => Yii::t('backend', 'First'),
            'lastPageLabel' => Yii::t('backend', 'Last')
        ],
        'columns' => [
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {update}',
                'contentOptions' => ['nowrap' => 'nowrap'],
                'urlCreator' => function ($action, $model, $key, $index) {
                    // using the column name as key, not mapping to 'id' like the standard generator
                    $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string)$key];
                    $params[0] = '/articles/ae-ext-article-bookmark' . '/' . $action;
                    $params['AeExtArticleBookmark'] = ['article_id' => $model->primaryKey()[0]];
                    return $params;
                },
                'buttons' => [

                ],
                'controller' => '/articles/ae-ext-article-bookmark'
            ],
            'id',
            [
                'class' => yii\grid\DataColumn::className(),
                'attribute' => 'play_id',
                'value' => function ($model) {
                    if ($rel = $model->getPlay()->one()) {
                        return Html::a($rel->id, ['/articles/ae-game-play/view', 'id' => $rel->id,], ['data-pjax' => 0]);
                    } else {
                        return '';
                    }
                },
                'format' => 'raw',
            ],
            'type',
        ]
    ])
    . '</div>'
    ?>
    <?php Pjax::end() ?>
    <?php $this->endBlock() ?>


    <?php $this->beginBlock('AeExtArticlePhotos'); ?>
    <div style='position: relative'>
        <div style='position:absolute; right: 0px; top: 0px;'>
            <?= Html::a(
                '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('backend', 'List All') . ' Article Photos',
                ['/articles/ae-ext-article-photo/index'],
                ['class' => 'btn text-muted btn-xs']
            ) ?>
            <?= Html::a(
                '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('backend', 'New') . ' Article Photo',
                ['/articles/ae-ext-article-photo/create', 'Article Photo' => ['article_id' => $model->id]],
                ['class' => 'btn btn-success btn-xs']
            ); ?>
        </div>
    </div>
    <?php Pjax::begin(['id' => 'pjax-AeExtArticlePhotos', 'enableReplaceState' => false, 'linkSelector' => '#pjax-AeExtArticlePhotos ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>
    <?=
    '<div class="table-responsive">'
    . \yii\grid\GridView::widget([
        'layout' => '{summary}{pager}<br/>{items}{pager}',
        'dataProvider' => new \yii\data\ActiveDataProvider([
            'query' => $model->getAeExtArticlePhotos(),
            'pagination' => [
                'pageSize' => 20,
                'pageParam' => 'page-aeextarticlephotos',
            ]
        ]),
        'pager' => [
            'class' => yii\widgets\LinkPager::className(),
            'firstPageLabel' => Yii::t('backend', 'First'),
            'lastPageLabel' => Yii::t('backend', 'Last')
        ],
        'columns' => [
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {update}',
                'contentOptions' => ['nowrap' => 'nowrap'],
                'urlCreator' => function ($action, $model, $key, $index) {
                    // using the column name as key, not mapping to 'id' like the standard generator
                    $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string)$key];
                    $params[0] = '/articles/ae-ext-article-photo' . '/' . $action;
                    $params['Article Photo'] = ['article_id' => $model->primaryKey()[0]];
                    return $params;
                },
                'buttons' => [

                ],
                'controller' => '/articles/ae-ext-article-photo'
            ],
            'id',
            'position',
            [
                'label' => 'Photo',
                'format' => 'html',
                'value' => function($model) {
                    if ( $model->photo ) {

                        if ( !file_exists(Helper::getUploadPath() . $model->photo) ) {
                            return 'File "' .$model->photo . '" doesn\'t exists';
                        }

                        return Html::img(Helper::getUploadURL() . $model->photo, ['width' => '100']);
                    }

                    return false;
                },
            ],
        ]
    ])
    . '</div>'
    ?>
    <?php Pjax::end() ?>
    <?php $this->endBlock() ?>


    <?= Tabs::widget(
        [
            'id' => 'relation-tabs',
            'encodeLabels' => false,
            'items' => [
                [
                    'label' => '<b class=""># ' . $model->id . '</b>',
                    'content' => $this->blocks['backend\modules\articles\models\AeExtArticle'],
                    'active' => true,
                ],
                [
                    'content' => $this->blocks['AeExtArticleBookmarks'],
                    'label' => '<small>Article Bookmarks <span class="badge badge-default">' . count($model->getAeExtArticleBookmarks()->asArray()->all()) . '</span></small>',
                    'active' => false,
                ],
                [
                    'content' => $this->blocks['AeExtArticlePhotos'],
                    'label' => '<small>Article Photos <span class="badge badge-default">' . count($model->getAeExtArticlePhotos()->asArray()->all()) . '</span></small>',
                    'active' => false,
                ],
            ]
        ]
    );
    ?>
</div>