<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\quizzes\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_quiz_question_option".
 *
 * @property string $id
 * @property string $question_id
 * @property string $answer
 * @property integer $answer_order
 * @property integer $is_correct
 *
 * @property \backend\modules\quizzes\models\AeExtQuizQuestion $question
 * @property string $aliasModel
 */
abstract class AeExtQuizQuestionOption extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_quiz_question_option';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['question_id', 'answer', 'answer_order'], 'required'],
            [['question_id', 'answer_order', 'is_correct'], 'integer'],
            [['answer'], 'string'],
            [['question_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\quizzes\models\AeExtQuizQuestion::className(), 'targetAttribute' => ['question_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'question_id' => Yii::t('backend', 'Question ID'),
            'answer' => Yii::t('backend', 'Answer'),
            'answer_order' => Yii::t('backend', 'Answer Order'),
            'is_correct' => Yii::t('backend', 'Is Correct'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuestion()
    {
        return $this->hasOne(\backend\modules\quizzes\models\AeExtQuizQuestion::className(), ['id' => 'question_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\quizzes\models\query\AeExtQuizQuestionOptionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\quizzes\models\query\AeExtQuizQuestionOptionQuery(get_called_class());
    }


}
