<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\quizzes\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_quiz".
 *
 * @property string $id
 * @property string $app_id
 * @property string $name
 * @property string $description
 * @property integer $valid_from
 * @property integer $valid_to
 * @property integer $active
 * @property integer $show_in_list
 * @property string $image
 * @property integer $save_to_database
 *
 * @property \backend\modules\quizzes\models\AeGame $app
 * @property \backend\modules\quizzes\models\AeExtQuizSet[] $aeExtQuizSets
 * @property string $aliasModel
 */
abstract class AeExtQuiz extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_quiz';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['app_id', 'name', 'description'], 'required'],
            [['app_id', 'valid_from', 'valid_to', 'active', 'show_in_list', 'save_to_database'], 'integer'],
            [['description'], 'string'],
            [['name', 'image'], 'string', 'max' => 255],
            [['app_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\quizzes\models\AeGame::className(), 'targetAttribute' => ['app_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'app_id' => Yii::t('backend', 'App ID'),
            'name' => Yii::t('backend', 'Name'),
            'description' => Yii::t('backend', 'Description'),
            'valid_from' => Yii::t('backend', 'Valid From'),
            'valid_to' => Yii::t('backend', 'Valid To'),
            'active' => Yii::t('backend', 'Active'),
            'show_in_list' => Yii::t('backend', 'Show In List'),
            'image' => Yii::t('backend', 'Image'),
            'save_to_database' => Yii::t('backend', 'Save To Database'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getApp()
    {
        return $this->hasOne(\backend\modules\quizzes\models\AeGame::className(), ['id' => 'app_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAeExtQuizSets()
    {
        return $this->hasMany(\backend\modules\quizzes\models\AeExtQuizSet::className(), ['quiz_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\quizzes\models\query\AeExtQuizQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\quizzes\models\query\AeExtQuizQuery(get_called_class());
    }


}
