<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var backend\modules\tickers\models\AeNotification $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="ae-notification-form">

    <?php $form = ActiveForm::begin([
    'id' => 'AeNotification',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-danger',
    'fieldConfig' => [
             'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
             'horizontalCssClasses' => [
                 'label' => 'col-sm-2',
                 #'offset' => 'col-sm-offset-4',
                 'wrapper' => 'col-sm-8',
                 'error' => '',
                 'hint' => '',
             ],
         ],
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute id_user -->
			<?= $form->field($model, 'id_user')->textInput(['maxlength' => true]) ?>

<!-- attribute id_channel -->
			<?= $form->field($model, 'id_channel')->textInput(['maxlength' => true]) ?>

<!-- attribute id_playaction -->
			<?= $form->field($model, 'id_playaction')->textInput(['maxlength' => true]) ?>

<!-- attribute app_id -->
			<?= $form->field($model, 'app_id')->textInput(['maxlength' => true]) ?>

<!-- attribute onesignal_msgid -->
			<?= $form->field($model, 'onesignal_msgid')->textInput(['maxlength' => true]) ?>

<!-- attribute action_id -->
			<?= $form->field($model, 'action_id')->textInput(['maxlength' => true]) ?>

<!-- attribute play_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'play_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\modules\tickers\models\AeGamePlay::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('backend', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['play_id'])),
    ]
); ?>

<!-- attribute menuid -->
			<?= $form->field($model, 'menuid')->textInput(['maxlength' => true]) ?>

<!-- attribute subject -->
			<?= $form->field($model, 'subject')->textarea(['rows' => 6]) ?>

<!-- attribute message -->
			<?= $form->field($model, 'message')->textarea(['rows' => 6]) ?>

<!-- attribute email_to -->
			<?= $form->field($model, 'email_to')->textInput(['maxlength' => true]) ?>

<!-- attribute parameters -->
			<?= $form->field($model, 'parameters')->textInput(['maxlength' => true]) ?>

<!-- attribute badge_count -->
			<?= $form->field($model, 'badge_count')->textInput(['maxlength' => true]) ?>

<!-- attribute manual_config -->
			<?= $form->field($model, 'manual_config')->textarea(['rows' => 6]) ?>

<!-- attribute sendtime -->
			<?= $form->field($model, 'sendtime')->textInput() ?>

<!-- attribute lastsent -->
			<?= $form->field($model, 'lastsent')->textInput() ?>

<!-- attribute debug -->
			<?= $form->field($model, 'debug')->textarea(['rows' => 6]) ?>

<!-- attribute shown_in_app -->
			<?= $form->field($model, 'shown_in_app')->textInput() ?>

<!-- attribute read_in_app -->
			<?= $form->field($model, 'read_in_app')->textInput() ?>

<!-- attribute repeated -->
			<?= $form->field($model, 'repeated')->textInput() ?>

<!-- attribute expired -->
			<?= $form->field($model, 'expired')->textInput() ?>

<!-- attribute os_success -->
			<?= $form->field($model, 'os_success')->textInput() ?>

<!-- attribute os_failed -->
			<?= $form->field($model, 'os_failed')->textInput() ?>

<!-- attribute os_converted -->
			<?= $form->field($model, 'os_converted')->textInput() ?>

<!-- attribute created -->
			<?= $form->field($model, 'created')->textInput() ?>

<!-- attribute updated -->
			<?= $form->field($model, 'updated')->textInput() ?>

<!-- attribute menu_id -->
			<?= $form->field($model, 'menu_id')->textInput(['maxlength' => true]) ?>

<!-- attribute type -->
			<?= $form->field($model, 'type')->textInput(['maxlength' => true]) ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => Yii::t('backend', 'AeNotification'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

