<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\items\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_items_images".
 *
 * @property string $id
 * @property string $item_id
 * @property integer $date
 * @property string $image
 * @property integer $featured
 * @property integer $image_order
 *
 * @property \backend\modules\items\models\AeExtItem $item
 * @property string $aliasModel
 */
abstract class AeExtItemsImage extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_items_images';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['item_id', 'image'], 'required'],
            [['item_id', 'date', 'featured', 'image_order'], 'integer'],
            [['image'], 'string', 'max' => 255],
            [['item_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\items\models\AeExtItem::className(), 'targetAttribute' => ['item_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'item_id' => Yii::t('backend', 'Item ID'),
            'date' => Yii::t('backend', 'Date'),
            'image' => Yii::t('backend', 'Image'),
            'featured' => Yii::t('backend', 'Featured'),
            'image_order' => Yii::t('backend', 'Image Order'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItem()
    {
        return $this->hasOne(\backend\modules\items\models\AeExtItem::className(), ['id' => 'item_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\items\models\query\AeExtItemsImageQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\items\models\query\AeExtItemsImageQuery(get_called_class());
    }


}
