<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 * @var yii\web\View $this
 * @var backend\modules\fitness\models\AeExtFitExercise $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="ae-ext-fit-exercise-form">

    <?php $form = ActiveForm::begin([
            'id' => 'AeExtFitExercise',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-danger',
            'fieldConfig' => [
                'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
                'horizontalCssClasses' => [
                    'label' => 'col-sm-2',
                    #'offset' => 'col-sm-offset-4',
                    'wrapper' => 'col-sm-8',
                    'error' => '',
                    'hint' => '',
                ],
            ],
        ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


            <!-- attribute app_id -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'app_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(backend\modules\fitness\models\AeGame::find()->all(), 'id', 'name'),
                [
                    'prompt' => Yii::t('backend', 'Select'),
                    'disabled' => (isset($relAttributes) && isset($relAttributes['app_id'])),
                ]
            ); ?>

            <!-- attribute name -->
            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

            <!-- attribute duration -->
            <?=
            $form->field($model, 'duration')->dropDownList(
                [
                    '30'=>'30 min',
                    '60'=>'60 min',
                    '90'=>'90 min',
                ],
                [
                    'prompt' => Yii::t('backend', 'Select'),
                ]
            ); ?>

            <!-- attribute category_id -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'category_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(backend\modules\fitness\models\AeExtFitProgramCategory::find()->all(), 'id', 'name'),
                [
                    'prompt' => Yii::t('backend', 'Select'),
                    'disabled' => (isset($relAttributes) && isset($relAttributes['category_id'])),
                ]
            ); ?>

            <!-- attribute article_id -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'article_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(backend\modules\fitness\models\AeExtArticle::find()->all(), 'id', 'title'),
                [
                    'prompt' => Yii::t('backend', 'Select'),
                    'disabled' => (isset($relAttributes) && isset($relAttributes['article_id'])),
                ]
            ); ?>

            <!-- attribute points -->
            <?= $form->field($model, 'points')->textInput() ?>
        </p>
        <?= Yii::$app->controller->renderPartial('movements-fields', [
            'component' => $component,
            'relations_json' => $relations_json
        ]); ?>
        <?php $this->endBlock(); ?>

        <?=
        Tabs::widget(
            [
                'encodeLabels' => false,
                'items' => [
                    [
                        'label' => Yii::t('backend', 'AeExtFitExercise'),
                        'content' => $this->blocks['main'],
                        'active' => true,
                    ],
                ]
            ]
        );
        ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Save')),
            [
                'id' => 'save-' . $model->formName(),
                'class' => 'btn btn-success'
            ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

