<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var backend\modules\fitness\models\AeExtFitExercise $model
*/
$copyParams = $model->attributes;

$this->title = Yii::t('backend', 'Ae Ext Fit Exercise');
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Ae Ext Fit Exercises'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('backend', 'View');
?>
<div class="giiant-crud ae-ext-fit-exercise-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?= Yii::t('backend', 'Ae Ext Fit Exercise') ?>
        <small>
            <?= Html::encode($model->name) ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
            '<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('backend', 'Edit'),
            [ 'update', 'id' => $model->id],
            ['class' => 'btn btn-info']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-copy"></span> ' . Yii::t('backend', 'Copy'),
            ['create', 'id' => $model->id, 'AeExtFitExercise'=>$copyParams],
            ['class' => 'btn btn-success']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('backend', 'New'),
            ['create'],
            ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
            . Yii::t('backend', 'Full list'), ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('backend\modules\fitness\models\AeExtFitExercise'); ?>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'app_id',
    'value' => ($model->app ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['/fitness/ae-game/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->app->name, ['/fitness/ae-game/view', 'id' => $model->app->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'AeExtFitExercise'=>['app_id' => $model->app_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
        'name',
        'duration',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'category_id',
    'value' => ($model->category ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['/fitness/ae-ext-fit-program-category/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->category->name, ['/fitness/ae-ext-fit-program-category/view', 'id' => $model->category->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'AeExtFitExercise'=>['category_id' => $model->category_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'article_id',
    'value' => ($model->article ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['/fitness/ae-ext-article/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->article->title, ['/fitness/ae-ext-article/view', 'id' => $model->article->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'AeExtFitExercise'=>['article_id' => $model->article_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
        'points',
    ],
    ]); ?>

    
    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('backend', 'Delete'), ['delete', 'id' => $model->id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . Yii::t('backend', 'Are you sure to delete this item?') . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
<?php $this->beginBlock('AeExtCalendarEntries'); ?>
<div style='position: relative'>
<div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('backend', 'List All') . ' Ae Ext Calendar Entries',
            ['/fitness/ae-ext-calendar-entry/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('backend', 'New') . ' Ae Ext Calendar Entry',
            ['/fitness/ae-ext-calendar-entry/create', 'AeExtCalendarEntry' => ['exercise_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div>
</div>
<?php Pjax::begin(['id'=>'pjax-AeExtCalendarEntries', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-AeExtCalendarEntries ul.pagination a, th a']) ?>
<?=
 '<div class="table-responsive">'
 . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider([
        'query' => $model->getAeExtCalendarEntries(),
        'pagination' => [
            'pageSize' => 20,
            'pageParam'=>'page-aeextcalendarentries',
        ]
    ]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('backend', 'First'),
        'lastPageLabel'  => Yii::t('backend', 'Last')
    ],
    'columns' => [
 [
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = '/fitness/ae-ext-calendar-entry' . '/' . $action;
        $params['AeExtCalendarEntry'] = ['exercise_id' => $model->primaryKey()[0]];
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => '/fitness/ae-ext-calendar-entry'
],
        'id',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'play_id',
    'value' => function ($model) {
        if ($rel = $model->play) {
            return Html::a($rel->id, ['/fitness/ae-game-play/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'type_id',
    'value' => function ($model) {
        if ($rel = $model->type) {
            return Html::a($rel->name, ['/fitness/ae-ext-fit-program-category/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'program_id',
    'value' => function ($model) {
        if ($rel = $model->program) {
            return Html::a($rel->name, ['/fitness/ae-ext-fit-program/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'recipe_id',
    'value' => function ($model) {
        if ($rel = $model->recipe) {
            return Html::a($rel->name, ['/fitness/ae-ext-food-recipe/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
        'notes',
        'points',
        'time',
        'completion',
]
])
 . '</div>' 
?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


<?php $this->beginBlock('AeExtFitExerciseComponents'); ?>
<div style='position: relative'>
<div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('backend', 'List All') . ' Ae Ext Fit Exercise Components',
            ['/fitness/ae-ext-fit-exercise-component/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('backend', 'New') . ' Ae Ext Fit Exercise Component',
            ['/fitness/ae-ext-fit-exercise-component/create', 'AeExtFitExerciseComponent' => ['exercise_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div>
</div>
<?php Pjax::begin(['id'=>'pjax-AeExtFitExerciseComponents', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-AeExtFitExerciseComponents ul.pagination a, th a']) ?>
<?=
 '<div class="table-responsive">'
 . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider([
        'query' => $model->getAeExtFitExerciseComponents(),
        'pagination' => [
            'pageSize' => 20,
            'pageParam'=>'page-aeextfitexercisecomponents',
        ]
    ]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('backend', 'First'),
        'lastPageLabel'  => Yii::t('backend', 'Last')
    ],
    'columns' => [
 [
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = '/fitness/ae-ext-fit-exercise-component' . '/' . $action;
        $params['AeExtFitExerciseComponent'] = ['exercise_id' => $model->primaryKey()[0]];
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => '/fitness/ae-ext-fit-exercise-component'
],
        'id',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'component_id',
    'value' => function ($model) {
        if ($rel = $model->component) {
            return Html::a($rel->name, ['/fitness/ae-ext-fit-component/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
]
])
 . '</div>' 
?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


<?php $this->beginBlock('AeExtFitExerciseComponents0s'); ?>
<div style='position: relative'>
<div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('backend', 'List All') . ' Ae Ext Fit Exercise Components0s',
            ['/fitness/ae-ext-fit-exercise-component/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('backend', 'New') . ' Ae Ext Fit Exercise Components0',
            ['/fitness/ae-ext-fit-exercise-component/create', 'AeExtFitExerciseComponent' => ['exercise_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div>
</div>
<?php Pjax::begin(['id'=>'pjax-AeExtFitExerciseComponents0s', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-AeExtFitExerciseComponents0s ul.pagination a, th a']) ?>
<?=
 '<div class="table-responsive">'
 . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider([
        'query' => $model->getAeExtFitExerciseComponents(),
        'pagination' => [
            'pageSize' => 20,
            'pageParam'=>'page-aeextfitexercisecomponents0s',
        ]
    ]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('backend', 'First'),
        'lastPageLabel'  => Yii::t('backend', 'Last')
    ],
    'columns' => [
 [
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = '/fitness/ae-ext-fit-exercise-component' . '/' . $action;
        $params['AeExtFitExerciseComponent'] = ['exercise_id' => $model->primaryKey()[0]];
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => '/fitness/ae-ext-fit-exercise-component'
],
        'id',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'component_id',
    'value' => function ($model) {
        if ($rel = $model->component) {
            return Html::a($rel->name, ['/fitness/ae-ext-fit-component/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
]
])
 . '</div>' 
?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


<?php $this->beginBlock('AeExtFitProgramExercises'); ?>
<div style='position: relative'>
<div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('backend', 'List All') . ' Ae Ext Fit Program Exercises',
            ['/fitness/ae-ext-fit-program-exercise/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('backend', 'New') . ' Ae Ext Fit Program Exercise',
            ['/fitness/ae-ext-fit-program-exercise/create', 'AeExtFitProgramExercise' => ['exercise_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div>
</div>
<?php Pjax::begin(['id'=>'pjax-AeExtFitProgramExercises', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-AeExtFitProgramExercises ul.pagination a, th a']) ?>
<?=
 '<div class="table-responsive">'
 . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider([
        'query' => $model->getAeExtFitProgramExercises(),
        'pagination' => [
            'pageSize' => 20,
            'pageParam'=>'page-aeextfitprogramexercises',
        ]
    ]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('backend', 'First'),
        'lastPageLabel'  => Yii::t('backend', 'Last')
    ],
    'columns' => [
 [
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = '/fitness/ae-ext-fit-program-exercise' . '/' . $action;
        $params['AeExtFitProgramExercise'] = ['exercise_id' => $model->primaryKey()[0]];
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => '/fitness/ae-ext-fit-program-exercise'
],
        'id',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'program_id',
    'value' => function ($model) {
        if ($rel = $model->program) {
            return Html::a($rel->name, ['/fitness/ae-ext-fit-program/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
        'week',
        'day',
        'priority',
        'time',
        'repeat_days',
]
])
 . '</div>' 
?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [
 [
    'label'   => '<b class=""># '.Html::encode($model->id).'</b>',
    'content' => $this->blocks['backend\modules\fitness\models\AeExtFitExercise'],
    'active'  => true,
],
[
    'content' => $this->blocks['AeExtCalendarEntries'],
    'label'   => '<small>Ae Ext Calendar Entries <span class="badge badge-default">'. $model->getAeExtCalendarEntries()->count() . '</span></small>',
    'active'  => false,
],
[
    'content' => $this->blocks['AeExtFitExerciseComponents'],
    'label'   => '<small>Ae Ext Fit Exercise Components <span class="badge badge-default">'. $model->getAeExtFitExerciseComponents()->count() . '</span></small>',
    'active'  => false,
],
[
    'content' => $this->blocks['AeExtFitExerciseComponents0s'],
    'label'   => '<small>Ae Ext Fit Exercise Components0s <span class="badge badge-default">'. $model->getAeExtFitExerciseComponents()->count() . '</span></small>',
    'active'  => false,
],
[
    'content' => $this->blocks['AeExtFitProgramExercises'],
    'label'   => '<small>Ae Ext Fit Program Exercises <span class="badge badge-default">'. $model->getAeExtFitProgramExercises()->count() . '</span></small>',
    'active'  => false,
],
 ]
                 ]
    );
    ?>
</div>
