<?php

use dmstr\bootstrap\Tabs;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;


/**
 * @var yii\web\View $this
 * @var backend\modules\fitness\models\AeExtFoodRecipe $model
 * @var yii\widgets\ActiveForm $form
 * @var $ingredients
 * @var $current_selection_ingredients
 * @var $steps
 * @var $current_selection_steps
 */


$use_validation = true;

if (isset($_GET['id'])) {
    $use_validation = false;
}

?>

<div class="ae-ext-food-recipe-form">

    <?php $form = ActiveForm::begin([
            'id' => 'AeExtFoodRecipe',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-danger',
            'fieldConfig' => [
                'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
                'horizontalCssClasses' => [
                    'label' => 'col-sm-2',
                    'offset' => 'col-sm-offset-4',
                    'wrapper' => 'col-sm-8',
                    'error' => '',
                    'hint' => '',
                ],
            ],
        ]
    );
    ?>

    <div>
        <?php $this->beginBlock('main'); ?>

        <p>

            <!-- attribute name -->
            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

            <!-- attribute type_id -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'type_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(backend\modules\fitness\models\AeExtFoodRecipeType::find()->all(), 'id', 'name'),
                [
                    'prompt' => Yii::t('backend', 'Select'),
                    'disabled' => (isset($relAttributes) && isset($relAttributes['type_id'])),
                ]
            )->label('Type'); ?>

            <!-- attribute photo -->
            <?= $form->field($model, 'photo', [
                'enableClientValidation' => $use_validation,
                // 'enableAjaxValidation' => $use_validation
            ])->fileInput(['accept' => 'image/*'])

            ?>

            <!-- attribute serve -->
            <?= $form->field($model, 'serve')->textInput()->label('Servings'); ?>

            <!-- attribute serve -->
            <?= $form->field($model, 'total_time')->textInput()->label('Total time (in minutes)'); ?>

            <!-- attribute difficult -->
            <?= $form->field($model, 'difficult')->dropDownList([
                'easy' => 'Easy',
                'medium' => 'Medium',
                'hard' => 'Hard'
            ], [
                'prompt' => Yii::t('backend', 'Select'),
                'disabled' => (isset($relAttributes) && isset($relAttributes['type_id'])),
            ])->label('Difficulty'); ?>

            <?= Yii::$app->controller->renderPartial('ingredients-fields', [
                'ingredients' => $ingredients,
                'current_selection' => $current_selection_ingredients,
            ]); ?>

            <?= Yii::$app->controller->renderPartial('step-fields', [
                'steps' => $steps,
                'current_selection' => $current_selection_steps,
            ]); ?>

        </p>

        <?php $this->endBlock(); ?>

        <?=
        Tabs::widget(
            [
                'encodeLabels' => false,
                'items' => [
                    [
                        'label' => Yii::t('backend', 'Food Recipe'),
                        'content' => $this->blocks['main'],
                        'active' => true,
                    ],
                ]
            ]
        );
        ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Save')),
            [
                'id' => 'save-' . $model->formName(),
                'class' => 'btn btn-success'
            ]
        );
        ?>
    </div>
    <?php ActiveForm::end(); ?>

</div>