<?php

use backend\components\Helper;
use dmstr\bootstrap\Tabs;
use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/**
 * @var yii\web\View $this
 * @var backend\modules\fitness\models\AeExtFoodRecipe $model
 */
$copyParams = $model->attributes;

$this->title = Yii::t('backend', 'Food Recipe');
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Food Recipes'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('backend', 'View');
?>
<div class="giiant-crud ae-ext-food-recipe-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?= Yii::t('backend', 'Food Recipe') ?>
        <small>
            <?= Html::encode($model->name) ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
                '<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('backend', 'Edit'),
                ['update', 'id' => $model->id],
                ['class' => 'btn btn-info']) ?>

            <?= Html::a(
                '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('backend', 'New'),
                ['create'],
                ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
                . Yii::t('backend', 'Full list'), ['index'], ['class' => 'btn btn-default']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('backend\modules\fitness\models\AeExtFoodRecipe'); ?>


    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'name',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'type_id',
                'value' => ($model->type ?
                    Html::a('<i class="glyphicon glyphicon-list"></i>', ['/fitness/ae-ext-food-recipe-type/index']) . ' ' .
                    Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> ' . $model->type->name, ['/fitness/ae-ext-food-recipe-type/view', 'id' => $model->type->id,]) . ' ' .
                    Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'AeExtFoodRecipe' => ['type_id' => $model->type_id]])
                    :
                    '<span class="label label-warning">?</span>'),
            ],
            [
                'label' => 'Photo',
                'format' => 'html',
                'value' => function ($model) {
                    if ($model->photo) {
                        return Html::img(Helper::getUploadURL() . $model->photo, ['class' => 'image_view']);
                    }

                    return false;
                },
            ],
            'serve',
            'difficult',
        ],
    ]); ?>

    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('backend', 'Delete'), ['delete', 'id' => $model->id],
        [
            'class' => 'btn btn-danger',
            'data-confirm' => '' . Yii::t('backend', 'Are you sure to delete this item?') . '',
            'data-method' => 'post',
        ]); ?>
    <?php $this->endBlock(); ?>



    <?php $this->beginBlock('AeExtFoodRecipeIngredients'); ?>
    <div style='position: relative'>
        <div style='position:absolute; right: 0px; top: 0px;'>
            <?= Html::a(
                '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('backend', 'List All') . ' Food Recipe Ingredients',
                ['/fitness/ae-ext-food-recipe-ingredient/index'],
                ['class' => 'btn text-muted btn-xs']
            ) ?>
            <?= Html::a(
                '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('backend', 'New') . ' Food Recipe Ingredient',
                ['/fitness/ae-ext-food-recipe-ingredient/create', 'AeExtFoodRecipeIngredient' => ['recipe_id' => $model->id]],
                ['class' => 'btn btn-success btn-xs']
            ); ?>
        </div>
    </div>
    <?php Pjax::begin(['id' => 'pjax-AeExtFoodRecipeIngredients', 'enableReplaceState' => false, 'linkSelector' => '#pjax-AeExtFoodRecipeIngredients ul.pagination a, th a']) ?>
    <?=
    '<div class="table-responsive">'
    . \yii\grid\GridView::widget([
        'layout' => '{summary}{pager}<br/>{items}{pager}',
        'dataProvider' => new \yii\data\ActiveDataProvider([
            'query' => $model->getAeExtFoodRecipeIngredients(),
            'pagination' => [
                'pageSize' => 20,
                'pageParam' => 'page-aeextfoodrecipeingredients',
            ]
        ]),
        'pager' => [
            'class' => yii\widgets\LinkPager::className(),
            'firstPageLabel' => Yii::t('backend', 'First'),
            'lastPageLabel' => Yii::t('backend', 'Last')
        ],
        'columns' => [
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {update}',
                'contentOptions' => ['nowrap' => 'nowrap'],
                'urlCreator' => function ($action, $model, $key, $index) {
                    // using the column name as key, not mapping to 'id' like the standard generator
                    $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string)$key];
                    $params[0] = '/fitness/ae-ext-food-recipe-ingredient' . '/' . $action;
                    $params['AeExtFoodRecipeIngredient'] = ['recipe_id' => $model->primaryKey()[0]];
                    return $params;
                },
                'buttons' => [

                ],
                'controller' => '/fitness/ae-ext-food-recipe-ingredient'
            ],
            'id',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
            [
                'class' => yii\grid\DataColumn::className(),
                'attribute' => 'ingredient_id',
                'value' => function ($model) {
                    if ($rel = $model->ingredient) {
                        return Html::a($rel->name, ['/fitness/ae-ext-food-ingredient/view', 'id' => $rel->id,], ['data-pjax' => 0]);
                    } else {
                        return '';
                    }
                },
                'format' => 'raw',
            ],
            'quantity',
        ]
    ])
    . '</div>'
    ?>
    <?php Pjax::end() ?>
    <?php $this->endBlock() ?>


    <?php $this->beginBlock('AeExtFoodRecipeSteps'); ?>
    <div style='position: relative'>
        <div style='position:absolute; right: 0px; top: 0px;'>
            <?= Html::a(
                '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('backend', 'List All') . ' Recipe Steps',
                ['/fitness/ae-ext-food-recipe-step/index'],
                ['class' => 'btn text-muted btn-xs']
            ) ?>
            <?= Html::a(
                '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('backend', 'New') . ' Recipe Step',
                ['/fitness/ae-ext-food-recipe-step/create', 'AeExtFoodRecipeStep' => ['recipe_id' => $model->id]],
                ['class' => 'btn btn-success btn-xs']
            ); ?>
        </div>
    </div>
    <?php Pjax::begin(['id' => 'pjax-AeExtFoodRecipeSteps', 'enableReplaceState' => false, 'linkSelector' => '#pjax-AeExtFoodRecipeSteps ul.pagination a, th a']) ?>
    <?=
    '<div class="table-responsive">'
    . \yii\grid\GridView::widget([
        'layout' => '{summary}{pager}<br/>{items}{pager}',
        'dataProvider' => new \yii\data\ActiveDataProvider([
            'query' => $model->getAeExtFoodRecipeSteps(),
            'pagination' => [
                'pageSize' => 20,
                'pageParam' => 'page-aeextfoodrecipesteps',
            ]
        ]),
        'pager' => [
            'class' => yii\widgets\LinkPager::className(),
            'firstPageLabel' => Yii::t('backend', 'First'),
            'lastPageLabel' => Yii::t('backend', 'Last')
        ],
        'columns' => [
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {update}',
                'contentOptions' => ['nowrap' => 'nowrap'],
                'urlCreator' => function ($action, $model, $key, $index) {
                    // using the column name as key, not mapping to 'id' like the standard generator
                    $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string)$key];
                    $params[0] = '/fitness/ae-ext-food-recipe-step' . '/' . $action;
                    $params['AeExtFoodRecipeStep'] = ['recipe_id' => $model->primaryKey()[0]];
                    return $params;
                },
                'buttons' => [

                ],
                'controller' => '/fitness/ae-ext-food-recipe-step'
            ],
            'id',
            'time',
            'description:ntext',
        ]
    ])
    . '</div>'
    ?>
    <?php Pjax::end() ?>
    <?php $this->endBlock() ?>


    <?= Tabs::widget(
        [
            'id' => 'relation-tabs',
            'encodeLabels' => false,
            'items' => [
                [
                    'label' => '<b class=""># ' . Html::encode($model->id) . '</b>',
                    'content' => $this->blocks['backend\modules\fitness\models\AeExtFoodRecipe'],
                    'active' => true,
                ],
                [
                    'content' => $this->blocks['AeExtFoodRecipeIngredients'],
                    'label' => '<small>Food Recipe Ingredients <span class="badge badge-default">' . $model->getAeExtFoodRecipeIngredients()->count() . '</span></small>',
                    'active' => false,
                ],
                [
                    'content' => $this->blocks['AeExtFoodRecipeSteps'],
                    'label' => '<small>Recipe Steps <span class="badge badge-default">' . $model->getAeExtFoodRecipeSteps()->count() . '</span></small>',
                    'active' => false,
                ],
            ]
        ]
    );
    ?>
</div>
