<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\tatjack\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_items_filters".
 *
 * @property string $id
 * @property string $play_id
 * @property string $category_id
 * @property integer $price_from
 * @property integer $price_to
 * @property string $tags
 * @property string $category
 * @property string $aliasModel
 */
abstract class AeExtItemsFilter extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_items_filters';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['play_id', 'category_id', 'price_from', 'price_to', 'tags', 'category'], 'required'],
            [['play_id', 'category_id', 'price_from', 'price_to', 'category'], 'integer'],
            [['tags'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'play_id' => Yii::t('backend', 'Play ID'),
            'category_id' => Yii::t('backend', 'Category ID'),
            'price_from' => Yii::t('backend', 'Price From'),
            'price_to' => Yii::t('backend', 'Price To'),
            'tags' => Yii::t('backend', 'Tags'),
            'category' => Yii::t('backend', 'Category'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\tatjack\models\query\AeExtItemsFilterQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\tatjack\models\query\AeExtItemsFilterQuery(get_called_class());
    }


}
