<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\tatjack\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_items_likes".
 *
 * @property integer $id
 * @property string $play_id
 * @property string $item_id
 * @property string $status
 *
 * @property \backend\modules\tatjack\models\AeGamePlay $play
 * @property \backend\modules\tatjack\models\AeExtItem $item
 * @property string $aliasModel
 */
abstract class AeExtItemsLike extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_items_likes';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['play_id', 'item_id', 'status'], 'required'],
            [['play_id', 'item_id'], 'integer'],
            [['status'], 'string', 'max' => 255],
            [['play_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\tatjack\models\AeGamePlay::className(), 'targetAttribute' => ['play_id' => 'id']],
            [['item_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\tatjack\models\AeExtItem::className(), 'targetAttribute' => ['item_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'play_id' => Yii::t('backend', 'Play ID'),
            'item_id' => Yii::t('backend', 'Item ID'),
            'status' => Yii::t('backend', 'Status'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlay()
    {
        return $this->hasOne(\backend\modules\tatjack\models\AeGamePlay::className(), ['id' => 'play_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItem()
    {
        return $this->hasOne(\backend\modules\tatjack\models\AeExtItem::className(), ['id' => 'item_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\tatjack\models\query\AeExtItemsLikeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\tatjack\models\query\AeExtItemsLikeQuery(get_called_class());
    }


}
