<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\tatjack\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "ae_ext_bookings".
 *
 * @property string $id
 * @property string $play_id
 * @property string $assignee_play_id
 * @property string $item_id
 * @property integer $date
 * @property integer $length
 * @property string $notes
 * @property string $status
 * @property integer $price
 * @property string $lat
 * @property string $lon
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \backend\modules\tatjack\models\AeGamePlay $play
 * @property \backend\modules\tatjack\models\AeGamePlay $assigneePlay
 * @property \backend\modules\tatjack\models\AeExtItem $item
 * @property string $aliasModel
 */
abstract class AeExtBooking extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_bookings';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['play_id', 'assignee_play_id', 'item_id', 'date', 'length', 'price'], 'integer'],
            [['date', 'length', 'notes', 'status', 'price', 'lat', 'lon'], 'required'],
            [['notes'], 'string'],
            [['lat', 'lon'], 'number'],
            [['status'], 'string', 'max' => 60],
            [['play_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\tatjack\models\AeGamePlay::className(), 'targetAttribute' => ['play_id' => 'id']],
            [['assignee_play_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\tatjack\models\AeGamePlay::className(), 'targetAttribute' => ['assignee_play_id' => 'id']],
            [['item_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\tatjack\models\AeExtItem::className(), 'targetAttribute' => ['item_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'play_id' => Yii::t('backend', 'Play ID'),
            'assignee_play_id' => Yii::t('backend', 'Assignee Play ID'),
            'item_id' => Yii::t('backend', 'Item ID'),
            'date' => Yii::t('backend', 'Date'),
            'length' => Yii::t('backend', 'Length'),
            'notes' => Yii::t('backend', 'Notes'),
            'status' => Yii::t('backend', 'Status'),
            'price' => Yii::t('backend', 'Price'),
            'lat' => Yii::t('backend', 'Lat'),
            'lon' => Yii::t('backend', 'Lon'),
            'created_at' => Yii::t('backend', 'Created At'),
            'updated_at' => Yii::t('backend', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlay()
    {
        return $this->hasOne(\backend\modules\tatjack\models\AeGamePlay::className(), ['id' => 'play_id']);
    }

    public function getPlayData( $play_id, $variable )
    {
        $data = \backend\modules\tatjack\models\AeGamePlayVariable::find()
            ->joinWith('variable')
            ->where([
                'play_id' => $play_id,
                'ae_game_variable.name' => $variable
            ])
            ->one();
        
        return $data->value;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAssigneePlay()
    {
        return $this->hasOne(\backend\modules\tatjack\models\AeGamePlay::className(), ['id' => 'assignee_play_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItem()
    {
        return $this->hasOne(\backend\modules\tatjack\models\AeExtItem::className(), ['id' => 'item_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\tatjack\models\query\AeExtBookingQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\tatjack\models\query\AeExtBookingQuery(get_called_class());
    }


}
