<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\tatjack\models\base;

use Yii;

/**
 * This is the base-model class for table "ae_ext_user_bid_item_images".
 *
 * @property string $id
 * @property string $bid_item_id
 * @property string $image
 * @property string $weight
 *
 * @property \backend\modules\tatjack\models\AeExtBidItem $bidItem
 * @property string $aliasModel
 */
abstract class AeExtUserBidItemImage extends \backend\models\CrudBase
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ae_ext_user_bid_item_images';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['bid_item_id', 'image'], 'required'],
            [['bid_item_id', 'weight'], 'integer'],
            [['image'], 'string', 'max' => 255],
            [['bid_item_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\tatjack\models\AeExtBidItem::className(), 'targetAttribute' => ['bid_item_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'bid_item_id' => Yii::t('backend', 'Bid Item ID'),
            'image' => Yii::t('backend', 'Image'),
            'weight' => Yii::t('backend', 'Weight'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBidItem()
    {
        return $this->hasOne(\backend\modules\tatjack\models\AeExtBidItem::className(), ['id' => 'bid_item_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\tatjack\models\query\AeExtUserBidItemImageQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\tatjack\models\query\AeExtUserBidItemImageQuery(get_called_class());
    }


}
