<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var backend\modules\products\models\AeExtProduct $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="ae-ext-product-form">

    <?php $form = ActiveForm::begin([
    'id' => 'AeExtProduct',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-danger'
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute app_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'app_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\modules\products\models\AeGame::find()->all(), 'id', 'name'),
    [
        'prompt' => Yii::t('backend', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['app_id'])),
    ]
); ?>

<!-- attribute amazon_product_id -->
			<?= $form->field($model, 'amazon_product_id')->textInput(['maxlength' => true]) ?>

<!-- attribute photo -->
            <?= $form->field($model, 'photo')->fileInput(['accept' => 'image/*']) ?>

<!-- attribute title -->
			<?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

<!-- attribute header -->
			<?= $form->field($model, 'header')->textarea(['rows' => 6]) ?>

<!-- attribute description -->
			<?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

<!-- attribute link -->
			<?= $form->field($model, 'link')->textarea(['rows' => 6]) ?>

<!-- attribute rating -->
			<?= $form->field($model, 'rating')->textInput() ?>

<!-- attribute price -->
			<?= $form->field($model, 'price')->textInput(['maxlength' => true]) ?>

<!-- attribute points_value -->
			<?= $form->field($model, 'points_value')->textInput() ?>

            <!-- attribute sorting -->
	        <?= $form->field($model, 'sorting')->textInput() ?>

<!-- attribute category_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'category_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\modules\products\models\AeExtProductsCategory::find()->all(), 'id', 'title'),
    [
        'prompt' => Yii::t('backend', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['category_id'])),
    ]
); ?>

<!-- attribute play_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'play_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\modules\products\models\AeGamePlay::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('backend', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['play_id'])),
    ]
); ?>

<!-- attribute featured -->
			<?= $form->field($model, 'featured')->textInput() ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => Yii::t('backend', 'AeExtProduct'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

