<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var backend\modules\tatjack\models\AeExtItemsReport $model
*/
$copyParams = $model->attributes;

$this->title = Yii::t('backend', 'Ae Ext Items Report');
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Ae Ext Items Reports'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('backend', 'View');
?>
<div class="giiant-crud ae-ext-items-report-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?= Yii::t('backend', 'Ae Ext Items Report') ?>
        <small>
            <?= $model->id ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <div class="pull-left">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
            . Yii::t('backend', 'Full list'), ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr />

    <?php $this->beginBlock('backend\modules\tatjack\models\AeExtItemsReport'); ?>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'reporter_id',
    'value' => ($model->getPlay()->one() ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['/tatjack/ae-game-play/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->getPlay()->one()->id, ['/tatjack/ae-game-play/view', 'id' => $model->getPlay()->one()->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'AeExtItemsReport'=>['play_id' => $model->play_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'item_id',
    'value' => ($model->getItem()->one() ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['/tatjack/ae-ext-item/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->getItem()->one()->name, ['/tatjack/ae-ext-item/view', 'id' => $model->getItem()->one()->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'AeExtItemsReport'=>['item_id' => $model->item_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'tattoo_owner_id',
    'value' => ($model->getItemOwner()->one() ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['/tatjack/ae-game-play/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->getItemOwner()->one()->id, ['/tatjack/ae-game-play/view', 'id' => $model->getItemOwner()->one()->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'AeExtItemsReport'=>['item_owner_id' => $model->item_owner_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
	    [
		    'class' => yii\grid\DataColumn::className(),
		    'attribute' => 'reason',
		    'value' => function ($model) {
                $data = @json_decode($model->reason, true);

                if ( $data ) {
	                return implode(', ', json_decode($model->reason, true));
                }

                return false;
		    },
		    'format' => 'raw',
	    ],
    ],
    ]); ?>

    
    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('backend', 'Delete'), ['delete', 'id' => $model->id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . Yii::t('backend', 'Are you sure to delete this item?') . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [
 [
    'label'   => '<b class=""># '.$model->id.'</b>',
    'content' => $this->blocks['backend\modules\tatjack\models\AeExtItemsReport'],
    'active'  => true,
],
 ]
                 ]
    );
    ?>
</div>
